NUTFes/FinanSu

view/next-project/package-lock.json, view/next-project/yarn.lock
package-lock.jsonとyarn.lockをGit管理に追加した
=> [add] package-lock.json and yarn.lock

Makefile
resolve #42 
Makefileを作成した．
`make build` だけで環境ができることを目的とした．
また， `make run` で npm installなどのコマンド（今後増えるかと思ったので）を走るようにした．
- `Makefile`
- `make build` で build & npm installができるか
- `make run` でnpm installが走るか
=> [add]Makefile(#42)

view/Dockerfile
resolve #41 
Dockerfileを編集して，nodeのバージョンを16.13にあげた
- `view/Dockerfile` 
- `docker compose build` と `docker compose up` を実行して問題なくコンテナが立ち上がるか
=> [fix]Dockerfile(#41)

view/next-project/src/pages/budgets/BudgetList.tsx, view/next-project/tsconfig.json
resolve #54 
tsconfigを修正した
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [fix]pathを修正し，@components/でコンポーネントを呼び出せるようにした(#54)

.gitignore, Makefile, api/.air.conf, api/Dockerfile, api/cmd/main.go, api/go.mod, api/go.sum, docker-compose.yml, mysql/db/activities.sql, mysql/db/budgets.sql, mysql/db/departments.sql, mysql/db/purchase_orders.sql, mysql/db/purchase_reports.sql, mysql/db/sources.sql, mysql/db/suponser_styles.sql, mysql/db/suponsers.sql, mysql/db/users.sql
とりあえずデータベースに接続できることと，接続した際のAPIのが飛ばせるかまで試しました．
- echoが生きてるか確認
`http://localhost:1323`
- 予算が返ってくるAPI
`http://localhost:1323/budgets`
- APIが取得できるかどうか
- データベースに接続できるかどうか
`[Failed] Not Connect to MySQL` が出る場合は
`docker compose up db`としてDBが立ち上がるのを待ってから
`docker compose up api`とするといい
解決策を考え中
- cmd/main.goしか触っておらず，べた書きになってます．ファイル分割やアーキテクチャは一切考えられていないため，とりあえず動くコードとなってます．今からきれいにしていくのでそこは一旦無視．
1. `docker  compose exec db bash`としてデータベースコンテナに直接入る．
2. `mysql -u root -p -h 127.0.0.1`と打って，パスワードを要求されるから`root`と入力
3. `show databases;`とするとデータベースの一覧が返ってくるので，`use finansu_db;`としてfinansu用のデータベースを選択
4. `show tables;`とするとfinansu_dbのテーブル一覧が返ってくるのでそれをテーブルの一覧を確認
5. あとはSQL実行 例）予算を全て取得の場合 `select * from budgets;`
=> データベースへの接続と予算を全て取得するAPIの作成

view/next-project/src/components/Header.tsx
resolve #43
ヘッダーの作成
- view/next-project/src/components/Header.tsx
-
-
- `URL`
- コンテナを立ち上てhttp://localhost:3000/budgets/BudgetListを確認してください．
-
-
=> [mod]Header編集(#43)

view/next-project/src/components/General/EditButton.tsx, view/next-project/src/pages/budgets/BudgetList.tsx
resolve #0
- view/next-project/src/components/General/EditButton.tsx
- view/next-project/src/pages/budgets/BudgetList.tsx
-
- `URL`
スクリーンショット
-
-
-
=> [add]編集ボタンの作成値コンポーネント化

view/next-project/src/components/General/PulldownButton.tsx, view/next-project/src/components/Header.tsx, view/next-project/src/pages/budgets/PurchaseList.tsx, view/next-project/src/pages/purchases/PurchaseList.tsx
resolve #13 
購入物品一覧ページを作成した．
- view/next-project/src/pages/budgets/PurchaseList.tsx
-
-
- `URL`
スクリーンショット
-コンテナを立ち上げて(http://localhost:3000/budgets/PurchaseList)にアクセスして確認お願いします．
-
-
=> [add] 購入物品一覧ページの作成 (#13)

api/cmd/main.go, view/next-project/src/pages/budgets/BudgetList.tsx, view/next-project/src/pages/example.tsx, view/next-project/src/utils/api_methods.ts
resolve #71
-
-
-
- `URL`
スクリーンショット
- [GET] http://localhost:1323/budgets
- [GET] http://localhost:1323/budgets/1
- [POST] http://localhost:1323/budgets?price=1000&year_id=1&source_id=1（みたいなかんじ）
- [PUT] http://localhost:1323/budgets/1?price=1000&year_id=1&source_id=1（みたいなかんじ）
- [DELETE] http://localhost:1323/budgets/1
=> [add] budgetのAPI作成(#71)

view/next-project/src/pages/example.tsx, view/next-project/src/utils/api_methods.ts
resolve #73 
フロントエンドでputメソッドを実装した
- view/next-project/src/pages/example.tsx
- view/next-project/src/utils/api_methods.tsx
- `localhost:3000/example`
スクリーンショット
- `view/next-project/src/pages/example.tsx` の36行目 `putData` の値を変更して、画面左上のPutボタンを押して値が更新されるか確認してほしい
=> [fix]フロントでputメソッドを実装(#73)

docker-compose.yml
resolve #75
- docker-compose.yml
-
- `URL`
スクリーンショット
- データベースが永続化かつ接続ができるか
-
-
=> データベースの永続化

view/next-project/src/components/General/RegistButton.tsx, view/next-project/src/pages/budgets/BudgetList.tsx
resolve #0
- view/next-project/src/components/General/RegistButton.tsx
-
-
- `URL`
スクリーンショット
-
-
-
=> [add]登録ボタンの作成

view/next-project/src/pages/purchases/PurchaseReport.tsx
resolve #17 
購入報告ページの作成
- view/next-project/src/pages/purchases/PurchaseReport.tsx
-
-
- `URL`
スクリーンショット
- コンテナを立ち上げてhttp://localhost:3000/purchases/PurchaseReportにアクセスして確認お願いします．
-
-
=> [add]購入報告ページの作成(#17)

api/cmd/main.go, mysql/db/fund_informations.sql, view/next-project/src/pages/api/fundInformations.ts, view/next-project/src/pages/fundinformationsExample.tsx, view/next-project/src/pages/purchases/PurchaseOrder.tsx, view/next-project/src/pages/purchases/PurchaseReport.tsx
resolve #82 
PurchaseOrderに変更して必要カラム追加
- view/next-project/src/pages/purchases/PurchaseOrder.tsx
-
-
- `URL`
スクリーンショット
- コンテナを立ち上げて http://localhost:3000/purchases/PurchaseOrder にアクセスして確認お願いします．
-
-
=> PurchaseOrderに変更して必要カラム追加

view/next-project/src/pages/budgets/BudgetList.tsx
resolve #99 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [mod]予算一覧をAPIから取得して表示(#99)

mysql/db/years.sql
resolve #89 
year.sqlを作成し、yearsテーブルを作成しました。
カラムは id year
- mysql/db/years.sql
-
-
- `URL`
スクリーンショット
- yearsテーブルが正常作成されているかの確認
-
-
自分でもできていることは確認しました
=> [Finish] Create years tables

api/internals/usecase/fund_information_usecase.go
resolve #0
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [add] usecaseのcommitし忘れ

view/next-project/src/pages/fundlist.tsx
resolve #95
学内募金の募金一覧ページを作成．
- view/next-project/src/pages/fundlist.tsx
-
-
- `URL`
スクリーンショット
- コンテナを立ち上げて "http://localhost:3000/fundlist" にアクセスして確認お願いします．
-
-
=> [fix] 募金一覧の作成 (#95)

view/next-project/src/pages/api/purchaseItem.ts, view/next-project/src/pages/purchaseitem.tsx, view/next-project/src/pages/purchaseitem/example.tsx
resolve #127 
purchaseitemの一覧ページを作成した。
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [add]purchaseitemの追加(#127)

view/next-project/src/components/General/OpenDeleteModalButton.tsx, view/next-project/src/components/General/OpenEditModalButton.tsx, view/next-project/src/components/General/PurchaseOrderDeleteModal.tsx, view/next-project/src/components/General/PurchaseOrderEditModal.tsx, view/next-project/src/components/General/RegistButton.tsx, view/next-project/src/pages/purchaseorder.tsx
resolve #134 
購入申請の編集機能を作成した。
画面読み込み時にsubmitの関数が走っているから、それを解決する。
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [WIP]purchaseorderの編集機能を追加(#134)

api/internals/domain/value_object.go, api/router/router.go
resolve #0
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [fix] minor fix

view/next-project/src/components/purchaseorder/PurchaseOrderDeleteModal.tsx, view/next-project/src/components/purchaseorder/PurchaseOrderEditModal.tsx
resolve #163 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [fix]PurchaseOrderの編集・削除モーダルのデザインを修正(#163)

view/next-project/src/components/purchaseorder/PurchaseOrderDetailModal.tsx, view/next-project/src/pages/purchaseorder.tsx
resolve #164 
購入申請の詳細モーダルを作成した
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [add]購入申請の詳細モーダルを作成(#164)

view/next-project/src/components/General/RegistModal.tsx, view/next-project/src/components/Header.tsx, view/next-project/src/components/purchaseorder/PurchaseOrderDeleteModal.tsx, view/next-project/src/components/purchaseorder/PurchaseOrderEditModal.tsx, view/next-project/src/components/purchasereport/PurchaseReportDeleteModal.tsx, view/next-project/src/components/purchasereport/PurchaseReportEditModal.tsx, view/next-project/src/pages/budgets.tsx, view/next-project/src/pages/budgets/example.tsx, view/next-project/src/pages/fundInformation/example.tsx, view/next-project/src/pages/fundlist.tsx, view/next-project/src/pages/purchaseitem.tsx, view/next-project/src/pages/purchaseitem/example.tsx, view/next-project/src/pages/purchaseorder/example.tsx, view/next-project/src/pages/purchasereport.tsx, view/next-project/src/pages/purchasereport/example.tsx
resolve #166 
ビルドエラーの解消
完全に対応はできていない
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [fix]npm run buildで発生するエラーを解決(#166)

api/drivers/server/server.go, docker-compose.prod.yml, view/next-project/next.config.js
resolve #174
デプロイしてもエラーを吐かないように修正した
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [mod]デプロイ作業(#174)

view/next-project/src/components/budget/BudgetDeleteModal.tsx, view/next-project/src/components/budget/BudgetEditModal.tsx, view/next-project/src/components/budget/OpenDeleteModalButton.tsx, view/next-project/src/components/budget/OpenEditModalButton.tsx, view/next-project/src/pages/budgets.tsx
resolve #177
- view/next-project/src/components/budget/BudgetDeleteModal.tsx
- view/next-project/src/components/budget/BudgetEditModal.tsx
- view/next-project/src/components/budget/OpenDeleteModalButton.tsx
- view/next-project/src/components/budget/OpenEditModalButton.tsx
- view/next-project/src/pages/budgets.tsx
- `URL`
スクリーンショット
-
-
-
=> [add]予算の編集と削除機能の追加(#177)

view/next-project/src/components/budget/BudgetAddModal.tsx, view/next-project/src/components/budget/OpenAddModalButton.tsx, view/next-project/src/pages/budgets.tsx
resolve #196 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [mod]予算登録のyearとsourceをAPIから取得した値に変更(#196)

api/externals/controller/activity_controller.go, api/externals/repository/activity_repository.go, api/internals/domain/activity.go, api/internals/domain/value_object.go, api/internals/usecase/activity_usecase.go, api/router/router.go, mysql/db/activities.sql
resolve #160
-
-
-
- `URL`
スクリーンショット
-
-
-
Dockerのせいで動作未確認。ぱおん。
=> 協賛活動一覧ページで使用するapiの作成

view/next-project/src/components/fund_informations/FundInformationsAddButton.tsx, view/next-project/src/components/fund_informations/FundInformationsAddModal.tsx, view/next-project/src/pages/api/fundInformations.ts, view/next-project/src/pages/fund_informations.tsx
resolve #199
- view/next-project/src/components/fund_informations/FundInformationsAddButton.tsx
- view/next-project/src/components/fund_informations/FundInforaikinoMacBook-Air F
- view/next-project/src/pages/api/fundInformations.ts
- view/next-project/src/pages/fund_informations.ts
- `URL`
スクリーンショット
-
-
-
=> [mod]募金の登録機能の作成

api/externals/controller/user_controller.go, api/externals/repository/user_repository.go, api/internals/domain/role.go, api/internals/domain/user.go, api/internals/usecase/user_usecase.go, api/router/router.go, mysql/db/roles.sql, mysql/db/users.sql
resolve #200 
domainにroleを追加。（但し、今回使用してない）
domainのuserにRoleIDを追加。
dbにrolesを作成。
dbのusersにrole_idを追加。
- mysql/db/roles.sql
- mysql/db/users.sql
-
- `URL`
スクリーンショット
-
-
-
=> issue200 Roleテーブルの作成とUserテーブルにrole_idカラムを追加

view/next-project/src/pages/fund_informations.tsx
resolve #204 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [add]権限ごとでcheckboxのチェック可否を判断(#204)

view/next-project/src/pages/fund_informations.tsx
resolve #233 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [mod]get_fund_informations_for_viewで取得した値を利用(#233)

view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/OpenAddModalButton.tsx, view/next-project/src/pages/fund_informations.tsx
resolve #237 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [mod]募金追加時に学科ごとに教員を選択(#237)

api/drivers/server/log.go, api/drivers/server/server.go, api/externals/controller/activity_controller.go, api/externals/repository/activity_repository.go, api/externals/repository/budget_repository.go, api/externals/repository/department_repository.go, api/externals/repository/fund_information_repository.go, api/externals/repository/mail_auth_repository.go, api/externals/repository/purchase_item_repository.go, api/externals/repository/purchase_order_repository.go, api/externals/repository/purchase_report_repository.go, api/externals/repository/session_repository.go, api/externals/repository/source_repository.go, api/externals/repository/sponsor_repository.go, api/externals/repository/sponsor_style_repository.go, api/externals/repository/teacher_repository.go, api/externals/repository/user_repository.go, api/externals/repository/year_repository.go, api/internals/domain/budget.go, api/internals/usecase/budget_usecase.go
resolve #242 
予算の構造体を変更しました。
- api/externals/repository/budget_repository.go
- api/internals/domain/budget.go
- api/internals/usecase/budget_usecase.go
- `URL`
スクリーンショット
-
-
-
=> 予算（get_budgets_for_view/:id）の構造体を修正する

view/next-project/src/pages/fund_informations.tsx
resolve #241 
-
-
-
- `URL`
スクリーンショット
-
-
-
=> [mod]チェックボックスが動作しない問題を解決し、局長チェック済みの合計金額を表示(#241)

view/next-project/src/components/General/RegistButton.tsx, view/next-project/src/components/General/RegistModal.tsx, view/next-project/src/components/auth/SignUpView.tsx, view/next-project/src/components/budget/BudgetAddModal.tsx, view/next-project/src/components/budget/BudgetEditModal.tsx, view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/FundInformationEditModal.tsx, view/next-project/src/components/user/EditModal.tsx
resolve #251 
- `URL`
スクリーンショット
-
-
-
=> [fix]npm run build error(#251)

view/next-project/src/components/General/SideNav.tsx, view/next-project/src/components/layout/MainLayout.tsx, view/next-project/src/pages/budgets.tsx, view/next-project/src/pages/fund_informations.tsx, view/next-project/src/pages/purchaseitem.tsx, view/next-project/src/pages/purchaseorder.tsx, view/next-project/src/pages/purchasereport.tsx
resolve #188 
- `URL`
スクリーンショット
-
-
-
=> [mod]サイドバーの作成(#188)

docker-compose.prod.yml, view/next-project/next.config.js
resolve #256 
- docker-compose.prod.yml
- next.config.js
を編集
- 本番環境の確認
ローカルDB対応は含まれません
=> [mod] prodction対応 (#256)

view/next-project/src/pages/fund_informations.tsx
resolve #0
- `URL`
スクリーンショット
-
-
-
=> [mod]role_idが2のときに募金のチェックボックスが表示されるように修正(#260)

view/next-project/src/pages/_app.tsx
resolve #265 
- `URL`
スクリーンショット
-
-
-
=> [mod]ログインしてないときにログイン画面に遷移(#265)

view/next-project/src/pages/_app.tsx
resolve #283 
- `URL`
スクリーンショット
-
-
-
=> [mod]ログインしていたら募金一覧ページに遷移(#283)

view/next-project/src/components/auth/SignUpView.tsx, view/next-project/src/pages/index.tsx
resolve #285 
- `URL`
スクリーンショット
-
-
-
=> [fix]npm run builで発生するエラーを解決(#285)

view/next-project/src/pages/fund_informations.tsx
resolve #287 
- `URL`
スクリーンショット
-
-
-
=> [fix]get_fund_informations_for_viewで何も取得できなくてもページを描画(#287)

view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/DisabledDeleteModalButton.tsx, view/next-project/src/components/fund_information/DisabledEditModalButton.tsx, view/next-project/src/components/fund_information/EditModal.tsx, view/next-project/src/components/fund_information/FundInformationDeleteModal.tsx, view/next-project/src/components/fund_information/FundInformationDetailModal.tsx, view/next-project/src/pages/fund_informations.tsx, view/next-project/src/utils/api/fundInformations.ts
resolve #292 
- `URL`
スクリーンショット
-
-
-
=> [fix]コメントアウトや不要部分を削除(#292)

api/drivers/db/gorm.go
resolve #0
- `URL`
スクリーンショット
-
-
-
=> [fix] gorm対応

.gitignore, docker-compose.prod.yml
resolve #294 
以下を編集
- docker-compose.prod.yml
- .gitignore
=> [mod] docker-compose.prod.yml .gitignore (#294)

view/next-project/src/components/General/LoadingButton.tsx, view/next-project/src/components/auth/SignInView.tsx, view/next-project/src/components/auth/SignUpView.tsx
resolve #298 
- `URL`
スクリーンショット
-
-
-
=> [mod]ログイン・新規登録ボタンのダブルクリックを禁止(#298)

view/next-project/src/pages/_app.tsx
resolve #304 
- `URL`
スクリーンショット
-
-
-
=> [fix]未ログイン時にログインページに遷移するように修正(#304)

view/next-project/src/components/auth/SignInView.tsx, view/next-project/src/components/auth/SignUpView.tsx
resolve #305 
ログイン失敗時にログインボタンが、新規登録失敗時に新規登録ボタンが押せない問題を解決
- `URL`
スクリーンショット
-
-
-
=> [fix]ログイン失敗時にボタンが押せなくなる問題を解決(#305)

api/tools/seeds/teacher_seeds.go
resolve #281 
- `URL`
スクリーンショット
-
-
-
=> [fix]teachers_seedを微修正(#281)

view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/pages/fund_informations.tsx
resolve #311 
教員の学科絞り込み機能を修正
- `URL`
スクリーンショット
-
-
-
=> [fix]更新された教員一覧に応じて教員の絞り込み昨日を修正(#311)

view/next-project/src/components/General/SideNav.tsx
resolve #272 
該当ページにいるときにそのページのサイドバーの色を変える
- `URL`
- コンテナを立ち上げて，'http://localhost:3000/fund_informations' にアクセスして確認お願いします．
-
-
=> [mod]該当ページにいるときサイドバーの色を変更(#272)

api/externals/controller/bureau_controller.go, api/externals/controller/department_controller.go, api/externals/repository/bureau_repository.go, api/internals/di/di.go, api/internals/domain/bureau.go, api/internals/usecase/bureau_usecase.go, api/router/router.go
resolve #303 
BureauのCRUDを作成しました。
- `URL`
スクリーンショット
-　BureauのCRUDができているかの確認
-
-
自分の環境での動作は確認済みです
=> [Create] Finish Bureau CRUD

view/next-project/src/pages/sponsorstyles/index.tsx, view/next-project/src/pages/teachers/index.tsx
resolve #327
- `URL`
スクリーンショット
-
-
-
=> [fix]resolve npm run build(#327)

view/next-project/src/components/teacher/AddModal.tsx, view/next-project/src/components/teacher/DeleteModal.tsx, view/next-project/src/components/teacher/EditModal.tsx, view/next-project/src/pages/purchaseitem.tsx, view/next-project/src/pages/purchasereports/index.tsx
resolve #331 
mainブランチのnpm run build時のエラーを解消
- `URL`
スクリーンショット
-
-
-
=> [fix]resolve build error

api/externals/controller/purhcase_order_controller.go, api/externals/repository/purchase_report_repository.go
http://localhost:1323/get_purchasereports_for_view/idの修正
- `URL`
スクリーンショット
-修正されているか確認お願いします
-
-
ブランチ切り忘れて、本来とは違うブランチからpushしてます
=> [FIX] get_purchase_reports/idの修正

view/next-project/src/pages/purchaseorders/index.tsx
resolve #340 
- `URL`
スクリーンショット
-
-
-
=> [mod]購入申請のテーブルの見た目を修正(#345)

view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
resolve #342 
- `URL`
スクリーンショット
-
-
-
=> [fix]購入申請のResetボタンの動作を修正(#342)

view/next-project/src/components/purchaseorders/DetailModal.tsx, view/next-project/src/pages/purchaseorders/index.tsx
resolve #324
購入申請の詳細モーダルを修正
- `URL`
スクリーンショット
-
-
-
=> [mod]購入申請の詳細モーダルを修正(#324)

api/externals/controller/user_controller.go, api/externals/repository/user_repository.go, api/internals/usecase/user_usecase.go, api/router/router.go
resolve #321 
- user情報を`POST`した際にできるレコードの取得
- user情報を`PUT`した際にできるレコードの取得
藤崎環境で動作確認済み
=> [issue321] userのpost, putを行った際にできるレコードの取得

view/next-project/src/components/purchasereports/EditModal.tsx
resolve #364 
- `URL`
スクリーンショット
-
-
-
=> [mod]purchasereportのカラムを編集可能に(#364)

view/next-project/src/components/auth/SignInView.tsx, view/next-project/src/components/auth/SignUpView.tsx
resolve #355 
ログイン・新規登録後に購入申請ページに遷移するように修正
=> [fix]ログイン/新規登録後に購入申請ページに遷移(#355)

view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/pages/purchasereports/index.tsx
resolve #377 
購入申請・報告の機能とデザインを修正
=> Fix/dodo/377 order report UI

view/next-project/src/components/global/context.tsx
resolve #382 
ログインしてない時にログインページにリダイレクトするように修正
=> [mod]未ログイン時にログインページにリダイレクト

.github/workflows/auto-prettier.yml, view/next-project/prettier.config.js
resolve #389 
- PR作成時・更新時に workflow を実行するよう変更
- commit message を変更
- `URL`
スクリーンショット
-
-
-
=> [fix]PR作成時にworkflowを実行しcommit commentを修正(#389)

.github/workflows/auto-prettier.yml
resolve #396 
cache を追加して npm  ci の時間を短縮
=> [mod]add cache npm(#396)

.github/workflows/golangci-lint.yml, .golangci.yml, api/externals/repository/session_repository.go
resolve #410 
- PRを出した時に、goファイルのlintチェックをする。修正点があれば、reviewerdogがその部分にコメントを残してくれる。
- `URL`
スクリーンショット
実際にciが通らないと以下のようになります。
- このPRのciが通っていればマージしてもらって大丈夫です。 
-
-
=> golangci-lint.yml追加

api/Dockerfile, docker-compose.yml, my.cnf
resolve #178 
- my.cnfにDBのcharの設定命令を記載
- docker-compose.ymlでmy.cnfをmountする
- `URL`
スクリーンショット
- DBコンテナとAPIコンテナを立ち上げて`http://localhost:1323/bureaus`を確認する
- 
-
-
=> mysql utf対応

api/docs/docs.go, api/externals/controller/bureau_controller.go, api/externals/repository/bureau_repository.go, api/internals/domain/bureau.go, api/internals/usecase/bureau_usecase.go, api/router/router.go
#424 
resolve #424 
- bureauのcreate,update時にそのレコードを返す修正を行なった
- budgetsのURIの修正
- bureauのswaggerへの追加
- swaggerのURIの整理
- swaggerでbureauに関するapiを確認する
- `http://localhost:1323/swagger/index.html#/`
=> bureau create, updateされたレコードを返す修正

api/docs/docs.go, api/externals/controller/fund_information_controller.go, api/externals/repository/fund_information_repository.go, api/internals/domain/fund_information.go, api/internals/usecase/fund_information_usecase.go, api/router/router.go
#426  
resolve #426
- fund_informationがcreate,updateされたときに、そのレコードを返す修正
- fund_informationのメソッドのリファクタリング
- fund_informationのswaggerの追加
- swaggerでAPIの動作に問題がないか確認する
- ファイルの変更点を確認し、メソッド名が適切かチェックする
-
=> #426-fund_information-fix

api/docs/docs.go, api/externals/controller/year_controller.go, api/externals/repository/year_repository.go, api/internals/usecase/year_usecase.go
resolve #435 
- yearのリプレイス 3ae7b247e207d57dc144a1160a77700cd4ef0c99
- yearのAPIをswaggerに記述 3ae7b247e207d57dc144a1160a77700cd4ef0c99
- `URL`
スクリーンショット
`docker compose up`でコンテナ起動
`http://localhost:1323/swagger/index.html#/`でyearが正常に返ってくるか確認する
=> yearのリプレイス完了

api/docs/docs.go, api/externals/controller/purhcase_order_controller.go, api/externals/repository/purchase_order_repository.go, api/internals/domain/purchase_order.go, api/internals/usecase/purchase_order_usecase.go, api/router/router.go
#428 
resolve #428
- purchase_orderのメソッドのリファクタリング
- メソッドの修正(create,udateしたレコードを返す)
- swaggerへのpurchase_orderの追加
- クエリ修正
- APIの動作確認
- メソッドのリファクタリングが適切か
=> 428-purchase_order

api/docs/docs.go, api/externals/controller/source_controller.go, api/externals/repository/source_repository.go, api/internals/domain/source.go, api/internals/usecase/source_usecase.go
#430 
resolve #430
- sourceがcreate,updateされた時レコードを返す
- sourceに関するリファクタリング
- sourceのswaggerへの追加
- `docker compose up`でコンテナを立ち上げる
- ブラウザで`http://localhost:1323/swagger/index.html#/source`を開いてsourceのAPIを叩き問題ないか確認する
- コードの修正に問題がないか確認する
=> 430-source

api/docs/docs.go, api/externals/controller/sponsor_controller.go, api/externals/repository/sponsor_repository.go, api/internals/domain/sponsor.go, api/internals/usecase/sponsor_usecase.go
#432 
resolve #432 
- sponsorをcreate,updateしたときにレコードを返す修正
- リファクタリング
- swaggerへの追加
スクリーンショット
- swaggerでapiの動作確認
- リファクタリングが正しいか確認
-
=> 432-sponsor

api/docs/docs.go, api/externals/controller/user_controller.go, api/externals/repository/user_repository.go, api/internals/domain/user.go, api/internals/usecase/user_usecase.go, api/router/router.go
#434 
resolve #434 
- create,updateした際にレコードを返す
- userに関するリファクタリング
- swaggerへの追加
- `URL`
スクリーンショット
- swaggerでuserに関するAPIを動作確認
- コードの修正に問題がないか確認する
-
=> 434-user-fix

api/docs/docs.go, api/externals/controller/department_controller.go, api/externals/repository/department_repository.go, api/internals/domain/department.go, api/internals/usecase/department_usecase.go, api/internals/usecase/user_usecase.go
#425 
resolve #425 
- create,updateしたときレコードを返す修正
- リファクタリング
- departmentのswaggerへの追加
- `user_usecase.go`の不要部分削除
- `URL`
- swaggerでのdapartmentに関する動作確認
- コードに問題がないか
=> 425-fix-department

api/externals/repository/session_repository.go, api/internals/usecase/mail_auth_usecase.go
resolve #458 
バグの原因調査スレ https://github.com/NUTFes/FinanSu/issues/450
ブラウザバックした状態だとsessionが削除されずに、ログインができないバグがあったので、修正した 093f8f448ad035763b097e620c5d3e736b95ab2a
- `URL`
スクリーンショット
- `docker compose up` コンテナ起動
- ログイン→ ブラウザバック→再ログインできるかの確認
=> ブラウザバック状態でログインできるように修正

api/docs/docs.go, api/externals/controller/purchase_item_controller.go, api/externals/repository/purchase_item_repository.go, api/internals/domain/purcahse_item.go, api/internals/domain/user.go, api/internals/usecase/purchase_item_usecase.go, api/router/router.go
#427 
resolve #427
- purchase_itemをcreate,updateした際レコードを返す修正
- リファクタリング
- swaggerへのpurchase_itemの追加
- swaggerでAPIの動作を確認する
- リファクタリングが適切か確認する
=> 427-purchase_item-fix

api/docs/docs.go, api/externals/controller/purchase_report_controller.go, api/externals/repository/purchase_report_repository.go, api/internals/domain/purchase_report.go, api/internals/usecase/purchase_report_usecase.go, api/router/router.go
#429 
resolve #429
- create,updateした際レコードを返す
- リファクタリング
- swaggerへの追加
- `URL`
スクリーンショット
- swaggerでAPIに問題がないか確認する
- コードの修正に問題がないか確認する
=> 429-fix-purchase_report

view/next-project/src/pages/budgets/index.tsx
none issue / minor fix
- budgetsのエンドポイントにミスがあり予算ページが見れなかったため修正
=> [fix] urlのtypoを修正

view/next-project/src/pages/fund_informations/index.tsx
resolve #391
- 募金ページをtailwind CSSにリプレイス
- 学内募金ページが見れるか
=> 募金ページのリプレイス

view/next-project/src/components/common/ChakraUIDropdown.tsx
resolve #496
- リロードするたびに出るRuntimeErrorを解消する
- recoilから撮ってきたuser nameのせいで発生してる
- sever側では""なのにcilent側だとユーザー名になってるせい
- suppressHydrationWarningをつけて押さえ込む
=> Unhandled Runtime Errorを解消する

view/next-project/src/components/layout/MainLayout/MainLayout.tsx, view/next-project/src/pages/fund_informations/index.tsx, view/next-project/src/pages/teachers/index.tsx, view/next-project/src/pages/users/index.tsx
resolve #497
- currentUserはrecoilから取ってこれるので、current_userを叩いているところを修正する
=> currentUserを叩いてるところをrecoilに置き換える

mysql/db/mail_auth.sql, mysql/db/users.sql
#500 
resolve #500 
開発用のアカウントを作成した。
作成したアカウント
1. 技大太郎1　総務局　users
email : `test1@test.com`
password : `123456`
2. 技大太郎2　総務局　admin
email : `test2@test.com`
password : `123456`
3. 技大太郎3　総務局　Finansu Directer
email : `test3@test.com`
password : `123456`
3. 技大太郎4　総務局　Finansu Staff
email : `test4@test.com`
password : `123456`
- `URL`
スクリーンショット
-  `docker compose down -v`でコンテナを削除(新しくコンテナを立ち上げるため)
-  `docker compose up`でコンテナ立ち上げ
-  ログイン画面でemailとpasswordでログインを確認する。
=> テストユーザーの追加

web/prod/config.yml
=> [mod] cloudflare config(#505)

.github/workflows/auto-labeling.yml, .github/workflows/auto-release.yml, .github/workflows/release.yml, test.yml
- 自動でリリースノートが作られるようにした
- PRのラベルからおしゃれに表示するようにした
- PRのラベルを自動でつけるようにした
- わかんない！
=> 自動リリース機能と自動ラベリング機能の実装

view/next-project/src/components/users/EditModal.tsx, view/next-project/src/components/users/OpenEditModalButton.tsx
- build時にlintによるエラーが発生したので修正する
=> [fix] import順修正

web/prod/config.yml
resolve #505 
`config.yml` を編集して，500番エラーの対策をした
- 本番環境が動作していることを確認
=> [mod] cloudflare config (#505)

docker-compose.prod.yml
resolve #541 
本番環境の `docker-compose.prod.yml`のcommand修正
- `URL`
スクリーンショット
本番環境で動くか確認したい場合は、開発環境でDockerfileとdocker-composeを本番環境と揃えたてあげれば確認できます
-
-
=> compose.prod修正

prod.api.Dockerfile, prod.view.Dockerfile
resolve #400
VIEWとAPIの全部乗せコンテナを作成した。
以下のコマンドで全部乗せコンテナが作れるか。※ VEIWはビルドが通る必要あり
```bash
docker build -f ./prod.api.Dockerfile -t finansu-prod-api  . 
docker build -f ./prod.view.Dockerfile -t finansu-prod-view .
```
以下のコマンドで全部乗せコンテナを立ち上げられるか ※ finansu.env はいつもの方法で入手してルートに配置して下さい
```bash
docker run --env-file=./finansu.env finansu-prod-api
docker run --env-file=./finansu.env finansu-prod-view
```
=> 全部乗せDockerfileの作成

view/next-project/src/components/budgets/ExpenseAddModal.tsx, view/next-project/src/components/budgets/ExpenseDeleteModal.tsx, view/next-project/src/components/budgets/ExpenseEditModal.tsx, view/next-project/src/components/budgets/OpenExpenseAddModalButton.tsx, view/next-project/src/components/budgets/OpenExpenseDeleteModalButton.tsx, view/next-project/src/components/budgets/OpenExpenseEditModalButton.tsx, view/next-project/src/components/common/AddButton/AddButton.tsx, view/next-project/src/components/common/DeleteButton.tsx, view/next-project/src/components/common/EditButton.tsx, view/next-project/src/components/sponsoractivities/OpenDeleteModalButton.tsx, view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx, view/next-project/src/pages/budgets/index.tsx, view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/pages/purchasereports/index.tsx, view/next-project/src/pages/sponsoractivities/index.tsx, view/next-project/src/utils/api/budget.ts
resolve #544
resolve #545 
resolve #546
- 支出を追加・削除・編集をできるようにする
- 協賛活動で編集・削除すると詳細モーダルも同時に開くのを修正する
- チェックボックスと編集・削除のdisabledを連動させる
test3でログインする
=> expenseを登録・削除・編集できるようにする+その他バグ修正

view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx, view/next-project/src/pages/sponsoractivities/index.tsx, view/next-project/src/type/common.ts
=> [fix] createAtのoptional対策を追加　リリース

mysql/db/users.sql, view/next-project/src/pages/fund_informations/index.tsx
resolve なし
- 編集ボタンと削除ボタンの正負が反転してたので修正
- チェックボックスをちゃんと押せて反映されるようにした
- `URL`
スクリーンショット
=> 募金ページのチェックボックス周りの修正

view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
resolve なし
- 協賛活動の追加モーダルの上部が見切れて閉じれない問題が発生した
=> 協賛活動追加モーダルが見切れないようにする

view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
- 備考を修正できるように
- 協賛活動の追加モーダルが見切れないように
=> 協賛関係修正リリース

view/next-project/src/components/budgets/DetailModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx, view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/pages/purchasereports/index.tsx, view/next-project/src/pages/sponsors/index.tsx
=> safari対応修正

view/next-project/src/pages/sponsoractivities/index.tsx
=> 協賛活動の合計値のNULL処理を追加

view/next-project/src/components/fund_information/EditModal.tsx, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/pages/fund_informations/index.tsx
resolve #0
募金ページと協賛活動ページの編集モーダルで登録されている担当者と所属している局が初期値になるようにした．
- `URL`
スクリーンショット
-
-
=> [fix]編集モーダルの担当者と所属局の修正

view/next-project/src/components/fund_information/EditModal.tsx, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/pages/purchasereports/index.tsx
resolve #0
購入申請と購入報告のチェックボックス修正
- `URL`
スクリーンショット
-
-
=> [Fix]チェックボックスの修正

mysql/feature/activity_query.sql
=> activty関係のsqlを追加

view/next-project/src/components/fund_information/AddModal.tsx
#623
resolve #623
先生の所属を変更に伴い初期値を変更するようにした
- `URL`
スクリーンショット
- 募金で先生の所属を変更して登録する
- 登録内容(先生)が正常か確認する
-
=> 先生の所属に伴う初期値の修正

.github/workflows/auto-build.yml
resolve #625 
build時に環境変数`CSR_API_URL`を`secrets. CSR_API_URL`から参照するようにした
- `URL`
スクリーンショット
-
-
=> build時に環境変数を参照するようにした

.github/workflows/auto-DockerHub-push.yml
resolve #625 
- `URL`
スクリーンショット
-
-
-
=> build時に引数CSR_API_URLを設定

.github/workflows/auto-DockerHub-push.yml
resolve #0
- `URL`
スクリーンショット
-
-
-
=> NEXT_PUBLIC_APP_ENVを参照するようにbuildさせる

prod.view.Dockerfile
=> Dockerfileに環境変数追加

view/next-project/src/components/purchasereports/PurchaseReportAddModal.tsx
resolve #648
購入報告登録モーダルで表示される購入者(任意)→購入者に変更した
- `URL`
スクリーンショット
- 任意が消えているか確認して欲しいです。
-
-
=> [fix]購入者(任意)を購入者に変更する

view/next-project/src/pages/fund_informations/index.tsx
resolve #682 
- 募金ページの年度切り替え機能実装
- ローカルで立ち上げ
- `http://localhost:3000/fund_informations`にアクセスし、年度切り替えができるか確認する
=> [feat]募金ページの年度切り替え機能実装

view/next-project/src/pages/purchaseorders/index.tsx
resolve #694  購入申請ページの購入申請一覧のテーブルの列「財務局長チェック」を削除し、調節しました
- `URL`
スクリーンショット
-
-
-
=> [fix]列名削除、調整

view/next-project/src/components/sponsors/SponsorAddModal.tsx, view/next-project/src/components/sponsors/SponsorEditModal.tsx
resolve #689 
企業名の名称が正しいものかを確認してもらうためのワンクッションとしてチェックボックスを追加しました。
- `URL`
スクリーンショット
- チェックを入れることで送信できるようになっているか
-
-
=> [fix] 企業名確認のためのチェックボックスを追記

view/next-project/src/components/budgets/ExpenditureAddModal.tsx, view/next-project/src/components/budgets/OpenExpenditureAddModalButton.tsx, view/next-project/src/pages/budgets/index.tsx, view/next-project/src/utils/api/budget.ts
resolve #714 
予算ページの支出元追加ボタン実装
- `URL`
スクリーンショット
-
-
=> 予算ページの支出元追加

view/next-project/src/pages/teachers/index.tsx
resolve #727
- `/teachers`ページで教師を所属ごとにフィルターをする機能を作成した
- `localhost:3000/teachers`で教師を所属でフィルターできるか確認する
=> 教師のフィルター機能作成

README.md
- HackMDを削除し、Notionに移行したためドキュメントのリンク先を変更した
- `URL`
スクリーンショット
-
-
-
=> [fix]README更新

view/next-project/src/pages/404.tsx
resolve #767 
- 404ページの作成
- ページが見つかりませんページを作成する
- FinanSuライクな感じでお願いします
|PC表示|モバイル表示|
|--|--|
|![FireShot Capture 005 -  - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/c2ba3242-8eeb-492f-bc2a-38d9a5efdbde)|![FireShot Capture 006 -  - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/9c0ec063-f547-4574-a999-eb9be26a3a22)|
- 存在しないページへアクセスすると、404ページが表示されるかを確認する。
- 「前のページに戻る」ボタンで元のページへ戻れるかを確認する。
=> [feat] 404ページの作成

view/next-project/src/components/common/FinanSuButton.tsx, view/next-project/src/stories/FinanSuButton.stories.tsx, view/next-project/src/stories/Modal.stories.tsx
- ModalのStorybookを作成した
- 小林さんが作ったstoriesのディレクトリ整理、エラー修正
- `URL`
スクリーンショット
=> ModalのStorybookの作成

view/next-project/src/stories/CloseButton.stories.tsx, view/next-project/src/stories/DeleteButton.stories.tsx, view/next-project/src/stories/Dropdown.stories.tsx, view/next-project/src/stories/PulldownButton.stories.tsx
resolve #0
既存のコンポーネントをStoribook上で確認できるようにするために、いくつかのコンポーネントに対応した.storiesファイルを追加しました。
- CloseButton
- DeleteButton
- Dropdown
- PulldownButton
- Storybookを起動させたとき、`localhost:6006`で以下のDocs、Primaryを見ることができるか
- CloseButton
- DeleteButton
- Dropdown
- PulldownButton
=> 既存コンポーネントに.storiesファイルを追加

docker-compose.prod.yml, docker-compose.yml
resolve #772 
- dockdrfileに書かれていた内容をfinansu.envにした
- `URL`
スクリーンショット
-
-
-
=> gmailのpassなどの環境変数をenvファイルにする

.github/workflows/auto-build.yml
resolve #0
- `URL`
スクリーンショット
-
-
-
=> [github actionsのワークフロー修正]nodeのバージョンアップ

.github/workflows/auto-build.yml, Makefile, api/prod.Dockerfile, docker-compose.local-prod.yml, docker-compose.prod.yml, docker-compose.yml, view/local-prod.Dockerfile, view/prod.Dockerfile
resolve #0
- `URL`
スクリーンショット
-
-
-
=> イメージビルドの簡略化

Makefile
resolve #811 
- makeファイルにコマンドの追加
`run-sb` storybookの起動
`run-sb-all` ビルド→起動→storybook起動のコマンド
`build-run` ビルドと起動
`del-vol` ボリューム削除
`del-vol-run` ボリューム削除→ビルドして起動
`del-all` 生成したコンテナ、イメージ、ボリューム、ネットワークを一括削除
`ent-db` DBに入る
=> Makeファイルにコマンド追加

Makefile
make run-sbでportを開けないと、localhostで接続できないため、コマンドを修正した
- `URL`
スクリーンショット
-
-
-
=> makefileの修正

README.md
resolve #0
- `URL`
スクリーンショット
-
-
-
=> [README]環境構築コマンドの修正

view/next-project/src/components/common/Modal.tsx, view/next-project/src/components/sponsors/DeleteModal.tsx, view/next-project/src/components/sponsors/SponsorAddModal.tsx, view/next-project/src/components/sponsors/SponsorEditModal.tsx
resolve #832 
- `URL`
スクリーンショット
-
-
-
=> 協賛企業のモーダルを閉じる

.gitignore, docker-compose.local-prod.yml
resolve #0
- `URL`
スクリーンショット
-
-
-
=> local-prodの設定追加

docker-compose.yml, view/next-project/src/components/sponsoractivities/FilterModal.tsx, view/next-project/src/pages/sponsoractivities/index.tsx
- バグの軽微な修正
- fixed→absolute
- scrollしたらフィルター中を示す点も動いた 
- フィルターモーダルの文面修正 回収状況→協賛金回収状況
- 協賛活動データの取得にローディングを追加
=> 協賛活動フィルターに関するバグ修正

view/next-project/src/components/sponsors/SponsorAddModal.tsx, view/next-project/src/components/sponsors/SponsorEditModal.tsx
resolve #880
<label>をつけてラベルを押しても反応するように変更。
- `URL`
スクリーンショット
-協賛企業ページの登録、編集モーダルのチェックボックスのラベルをクリックしてもチェックがつくか
=> 企業ページの登録時・編集時に「企業名が正確である。」のラベルをクリックしてもチェックがつくようにする

view/next-project/package-lock.json, view/next-project/package.json, view/next-project/src/components/common/SideNav.tsx, view/next-project/src/constants/linkItem.tsx
サイドバーを変更しました。
サイドバーを押した際にnext/linkを使うように変更しました。
サイドバーの不要な項目を削除し、新規ページの項目を追加しました。
募金活動のアイコンを追加するためにreact-iconのバージョンを5.4.0に更新しました。
サイドバーを使ったページ移動をスムーズにするためにnext/linkに変更しました。
-
-
-
=> サイドバーの変更を行いました。]

api/internals/usecase/festival_item_usecase.go
- 支出をチェック済でなくても、計算に含めるようにした
-
-
-
=> 支出をチェック済でなくても計算する

api/externals/repository/buy_report_repository.go, api/generated/openapi_gen.go, api/internals/usecase/buy_report_usecase.go, openapi/openapi.yaml
resolve #0
- `URL`
スクリーンショット
- fileNameも返ってきてたらok
-
-
=> Get buy_reports/details時にfileNameも返すように修正

.gitignore, compose.prod.db.yml
resolve #0
- `URL`
スクリーンショット
-
-
-
=> feat: 本番用のDBのymlを追加

view/next-project/next.config.js
resolve #0
- `URL`
スクリーンショット
-
-
-
=> fix: コードの可読性を向上

api/externals/repository/abstract/abstract_repository.go, api/externals/repository/financial_record_repository.go
resolve #0
- GET[/financial_records](http://localhost:8000/#/financial_record/get_financial_records)
- 予算管理の局一覧で集計が間違っているので、クエリを修正した
- WITH句を使いたいが、goquのWithとdialectの相性が悪いため、クエリを用意した
- 参考 https://github.com/doug-martin/goqu/issues/370 
- ただクエリの組み立ては、prepared statementで行う
- `URL`
- GET[/financial_records](http://localhost:8000/#/financial_record/get_financial_records)
- 局を取得して、データは問題ないか確認する
=> [バグ修正]予算管理の局のバグ修正

api/internals/usecase/festival_item_usecase.go
resolve #0
- マイページで予算が増えていくバグの修正
- 購入報告の個数*予算になっていたため、予算の加算を購入物品ごとに行うことにした
- またマイページの部門が変わる事象のバグも対応した
-
-
-
=> [バグ修正]マイページのバグ修正

.github/workflows/golangci-lint.yml, .golangci.yml, api/internals/usecase/division_usecase.go
resolve #0
- https://github.com/NUTFes/FinanSu/pull/940 でlintが落ちているため修正
- `URL`
スクリーンショット
-
-
-
=> golangciのlintエラー対応

.github/dependabot.yml
resolve #0
- パッケージの依存関係を自動で更新してくれるdependabotの導入
https://docs.github.com/ja/code-security/dependabot/working-with-dependabot
- `URL`
スクリーンショット
-
-
-
=> dependabotの設定追加

.github/workflows/auto-assign.yml
resolve #0
- ワークフローでPR発行者をアサインする
- `URL`
スクリーンショット
-
-
-
=> 自動アサインワークフロー追加
