NUTFes/FinanSu

view/next-project/src/components/General/PulldownButton.tsx, view/next-project/src/components/Header.tsx
resolve #64 
ヘッダー右側にある下矢印のアイコンをボタン化，コンポーネント化する．
-view/next-project/src/components/Header.tsx
-view/next-project/src/components/General/PulldownButton.tsx
-
- `URL`
スクリーンショット
-動作確認をお願いします．
-
-
=> [mod] 矢印アイコンをボタン化 (#64)

api/externals/controller/purhcase_order_controller.go, api/externals/repository/purchase_order_repository.go, api/externals/repository/purchase_report_repository.go, api/internals/usecase/purchase_order_usecase.go, api/router/router.go
resolve #320 
`purchaseorders`を`post`または、`put`した際にできるレコードを取得する機能の作成
- `URL`
スクリーンショット
postman等で以下のようなAPIをたたく
- post
`http://localhost:1323/get_post_purchaseorder_record?deadline="test-DeadLine-post"&user_id=3&finance_check=true`
- put 
`http://localhost:1323/get_post_purchaseorder_record/id?deadline="test-DeadLine-put"&user_id=2&finance_check=true`
藤崎の環境では動作確認済み
=> [issue320] purchaseordersのpost,putしたレコードの取得機能の作成

api/externals/controller/purchase_report_controller.go, api/externals/repository/purchase_report_repository.go, api/internals/usecase/purchase_report_usecase.go, api/router/router.go
resolve #359 
・`purchaseReport`を`post`した際に作成されるレコードの取得
・`purchaseReport`を`puy`した際に更新されるレコードの取得
をたたきpostした際に作成されるレコードを取得できるか
をたたきputした際に更新されるレコードを取得できるか
入力フィールド例
```
"user_id": 6,
"discount": 200,
"addition": 300,
"finance_check": true,
"remark": "test-remark",
"purchase_order_id": 3,
```
藤崎環境で動作確認済み
=> [issue359] purchasereportをpostとputした際のレコード取得

api/docs/docs.go, api/externals/controller/budget_controller.go, api/externals/repository/budget_repository.go, api/internals/domain/budget.go, api/internals/usecase/budget_usecase.go, api/router/router.go
resolve #417 
- repository, usecase, controller, router, domainにかけてメソッド名や変数名の修正
- **budgetに紐づくyearとsourceのデータを取得するURIも変わっているので、フロントでも修正をお願いします！**
- `URL`
スクリーンショット
- `make run-api`
- `http://localhost:1323/swagger/index.html#/`にて確認お願いします。swaggerの使い方が分からない場合は聞いてください。
=> Create, Update時にcreate, updateされたレコードを返す修正

api/docs/docs.go, api/externals/controller/budget_controller.go, api/externals/repository/budget_repository.go, api/internals/usecase/budget_usecase.go, api/router/router.go
#440 
resolve #440 
- swaggerの`/budgets/details`の追加
- swgger　`/budgets/{id}/details`→`/budgets/details/{id}`
- `ShowBudgetDetail`のメソッド名の変更 (末尾にByIdを追加)
- `ShowBudgetDetails`(budgetに紐づく全件データの取得)の実装
- swaggerよりapiを叩き動作に問題ないか確認する
- (budgetとyearsとsourcesのテーブルにデータが1つしかない可能性があるためデータを追加してからテストを行う)
- メソッド名を変更しているため問題ないか確認する
=> budgetに紐づくデータの全件取得

view/next-project/src/components/budgets/AddModal.tsx, view/next-project/src/components/budgets/EditModal.tsx, view/next-project/src/constants/sources.ts, view/next-project/src/pages/budgets/index.tsx
resolve #462 
予算一覧ページに収入と支出のタブ追加
- `[URL](http://localhost:3000/budgets)`
- コンテナを立ち上げて，'http://localhost:3000/budgets'にアクセスして確認お願いします．
-
-
- 支出側のカラムとかは全部適当です．
- 「予算」と「支出」でタブ分けするより，「予算」一覧ページ内で「支出」と「収入」をタブ分けした方がいい気がします．
=> [mod]予算一覧ページにタブ追加(#462)

api/externals/repository/year_repository.go
resolve #463 
yearReposityの構造体を修正した。
- `URL`
スクリーンショット
- `make run-api`で起動　yearのCRUDがswagger上で動作すれば問題ない
-
-
=> yearRepositoryのstructの修正

api/internals/usecase/expense_usecase.go, mysql/db/expense.sql
#523
resolve #523
- `/expenses/details`のAPIの返すpurchase_itemsのpurchase_order_idが正しくなかったため修正した。
- expenseのtotalPriceを更新する際tmp,tmp2という2つのテーブルを使用していたが、計算に使うテーブルであるテンポラリテーブルにしてストアドプロシージャ内のみで定義、削除するようにした。
- `URL`
スクリーンショット
- `/expenses`のAPIを叩き動作に問題がないか確認する。
-
-
=> expenseAPIの修正

docker-compose.prod.yml, web/prod/config.yml
apiの起動コマンドにstart.shを使っていたが、不必要であるので、`go run`コマンドに置き換える
=> api起動コマンド修正リリース

api/docs/docs.go, api/externals/controller/activity_controller.go, api/externals/controller/activity_style_controller.go, api/externals/repository/activity_repository.go, api/externals/repository/activity_style_repository.go, api/internals/di/di.go, api/internals/domain/activity.go, api/internals/domain/activity_style.go, api/internals/usecase/activity_style_usecase.go, api/internals/usecase/activity_usecase.go, api/router/router.go, mysql/db/activities.sql
#572
resolve #572
協賛活動と協賛スタイルが多対多の関係になるように中間テーブルactivity_styleテーブルを作成した。
activity_styleに関するAPIの作成(CRUD)
activity_styleのswaggerへの追加
`/activity/details`を叩いた際、複数の協賛スタイルが結びつくようにした。
協賛活動の詳細
中間テーブル(活動とスタイルを結びつけるためには、このレコードを追加する必要がある)
中間テーブルのAPIについて
GET `/activity_styles`
中間テーブルの一覧を取得
POST  `/activity_styles`
中間テーブルにレコードの追加
GET `/activity_styles/:id`
idで指定されたレコードを取得
PUT `/activity_styles/:id`
idで指定されたレコードを修正
DELETE `/activity_styles/:id`
idで指定されたレコードを削除
- `URL`
スクリーンショット
- `docker compose down -v` → `docker compose up`の順でコンテナ起動
- swaggerで以下を確認する
- 中間テーブル`/activity_styles`の操作ができるか
- `/activities/details`で複数の協賛スタイルが取得できているか
-
=> 協賛活動のAPIの修正

view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx, view/next-project/src/pages/budgets/index.tsx
resolve #573 
そのデザインを
- 学生が作るのか
- 企業が作るのか
- 去年のままなのか
を選べるようにする
- オプションが「なし」の場合の備考欄
- デザイン作成者
- 学生が作るならその掲載内容の入力
- オプションが「ポスター」の場合の備考欄
- デザイン作成者
- 学生が作るならその掲載内容の入力
- ポスターはパンフレット内容を拡大したもの
- オプションが「クーポン」の場合
- デザイン作成者
- 学生が作るならその掲載内容の入力
- クーポンの詳細を入力
=> デザインを誰が作るのかの選択肢を増やす

view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
resolve #583 
協賛活動の登録時に備考欄が編集できなかったので解決しました。
`newRemark` を更新する `useEffect` に `formData` が入ってたから、 `formData` を編集した時に `newRemark` が更新されて変更できないようになってたっぽいです。
- http://localhost:3000/sponsoractivities
https://github.com/NUTFes/FinanSu/assets/71711872/a2b185ee-6cb7-4224-a74b-0cb7735822d1
Slackでは「協賛活動の登録・編集時に備考欄が編集できない」とあったが、動作確認したところ編集モーダルでは備考欄の編集ができたので今回は触れてないです。
本番環境で動作確認したけど、編集モーダルの備考欄は編集できました。
=> [fix] 協賛活動の登録時に備考が編集できない問題を解決(#583)

view/next-project/src/components/budgets/DetailModal.tsx, view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/pages/purchasereports/index.tsx, view/next-project/src/pages/sponsors/index.tsx
#587 
resolve #587 
- safariで開くと、テーブルが崩れている時があるため修正する。
- 原因
- tailwindでclassにw-max+table-fixedを当てるとwidthが1になってしまっていた。
- したがってsp版ではlassにw-max+table-autoを当てる
- 
- `URL`
スクリーンショット
- safariで`localhost:3000`を開き、テーブルが崩れていないか確認する
-
-
=> safariテーブル調整

api/docs/docs.go, api/externals/controller/sponsor_controller.go, api/externals/repository/sponsor_repository.go, view/next-project/src/utils/api/sponsor.ts
#590 
resolve #590 
- フロントから受け取った文字列をエスケープして、'や"が含まれていても登録できるようにした
- 協賛企業の登録、修正の際データをクエリパラメータで送っていたのをbodyパラメータで送るようにした。
- 上に伴うswaggerの修正
- 協賛企業ページで'や"を含む文字列を登録、修正して動作を確認する。
- swaggerで`/sponsor`のpost、putができるか確認する
=> 協賛企業登録のエスケープ処理

view/next-project/src/components/sponsoractivities/DetailModal.tsx, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/OpenEditModalButton.tsx, view/next-project/src/pages/sponsoractivities/index.tsx
resolve なし
- 紐づいてる協賛スタイルがない場合でも画面が表示できるようにした
- [swagger](http://localhost:1323/swagger/index.html#/)からactivitiesをpostする
- 本来はactivity_styleもpostする必要があるが、今回はわざとしない
- FinanSuにログインし、協賛活動ページに移動する
- ページと各モーダルが開くかどうか
=> activityのstyleがない場合にエラーが出ないようにする

view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
#594 
resolve #594 
企業ブースかつ協賛スタイルの配列サイズが1 の場合、オプションを選択不可にした。
- 協賛活動ページで追加、編集を行う
- スタイルが企業ブースのみの時、オプションが選択不可、企業ブース+他のスタイルの時オプションを選択できるか確認する。
=> 企業ブース以外もある場合は選択可能に

api/externals/repository/purchase_order_repository.go, api/internals/usecase/purchase_order_usecase.go
#600 
resolve #600
- 購入申請を削除するapi `DELETE` `/purchase_orders/{id}`を叩くと、それに紐づくitemsとreportも削除する。
- `URL`
スクリーンショット
- swaggerで`DELETE` `/purchase_orders/{id}`を叩く
- purchase_orderに紐づいたpurchase_items, purchase_reportsが削除されているか確認する。
=> purchaseのdeleteの削除の修正

view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/EditModal.tsx, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx
resolve #552 
募金ページと協賛活動の追加モーダルに担当者を局ごとに絞り込む機能を追加
- `URL`
-
=> [add]ユーザの絞り込み機能追加

api/docs/docs.go, api/externals/controller/activity_controller.go, api/externals/repository/activity_repository.go, api/internals/domain/activity.go, api/internals/usecase/activity_usecase.go, mysql/db/activities.sql, view/next-project/src/components/sponsoractivities/DetailModal.tsx, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx, view/next-project/src/constants/designers.ts, view/next-project/src/pages/sponsoractivities/index.tsx, view/next-project/src/type/common.ts
#615 
resolve #615
- activityテーブルにカラム追加,
- `design` :誰が作ったかを表す。int型　0:なし 1:学生 2:企業 3:去年
- `url` :広告データのurl、string型
- カラムの追加に伴うAPIの修正
- 協賛活動ページの表にデザイン追加
- 作成の矢印からgoogleドライブに遷移 
- 協賛活動ページの追加モーダルの修正
- デザイン作成とリンクの入力フォーム追加
- 備考の動的生成の修正
- 協賛活動ページの詳細モーダルの修正
- デザイン作成とリンクの追加
- 協賛活動ページの修正モーダルの修正
- デザイン作成とリンクの入力フォーム追加
- 備考の動的生成の修正
- `URL`
スクリーンショット
- データベースのスキーマを変更しているため、DBコンテナのvolume削除
- `docker compose down -v`
- コンテナ立ち上げ　`docker compose up`
- テスト１　apiの確認
- swaggerでactivityのapiの動作が適切であるか確認する
- テスト2　協賛活動ページの確認
- 表にデザインが追加されている確認する
- デザインのリンクの確認(urlは自分で追加してください)
- スマホページの確認
- テスト3　追加モーダルの確認
- 追加モーダルにデザインとurlを入力する欄があるか
- 備考動的生成の動作の確認(あとで詳しく書きます)
- レコードの追加ができるか
- sp版でもできるか
- テスト4　修正モーダルの確認
- 修正モーダルにデザインとurlを入力する欄があるか
- 備考動的生成の動作の確認(あとで詳しく書きます)
- レコードの修正ができるか
- sp版でもできるか
- テスト4　詳細モーダルの確認
- …
=> 制作局が使いやすくするための仕様追加

view/next-project/src/components/common/Title.tsx, view/next-project/src/pages/sponsoractivities/index.tsx, view/next-project/src/utils/createActivityCsv.ts, view/next-project/src/utils/createCsv.ts, view/next-project/src/utils/downloadFile.ts
resolve #616
- 協賛活動のデータをcsvでダウンロードできるようにした
- https://nut-m-e-g.slack.com/archives/C020WQ3GY07/p1687530255938499
- 協賛活動ページに移動
=> 協賛活動ページにcsvダウンロード機能を追加

view/next-project/src/pages/purchasereports/index.tsx, view/next-project/src/utils/createPurchaseReportCsv.ts
購入報告の内容をSCV出力させる
- `URL`
スクリーンショット
- 購入申請一覧(2022)_20230808.csv
```
ID,報告した局,報告日,購入日,合計金額,財務局長チェック,購入物品 (品名/値段/数量/財務局長チェック),備考
1,企画局,2023-06-19,2022-3-28,100100,○,ビンゴ用品/30000円/3個/○ ， マイク/10000円/1個/○,test-remark
2,企画局,2023-06-19,2022-2-22,10000,,ビンゴ景品/10000円/1個/○ ， ヒーロースーツ/20000円/2個/×,test-remark2
3,総務局,2023-06-19,2022-4-6,40400,○,机/20000円/2個/○ ， 椅子/30000円/3個/×,test-remark3
4,情報局,2023-06-19,2022-3-28,100400,○,酒/10000円/10個/○,test-remark3
5,制作局,2023-06-19,2022-4-6,400,○,封筒/100円/100個/×,test-remark3
6,渉外局,2023-06-19,2022-4-6,5400,○,領収書/100円/50個/○,test-remark3
```
-
- 出力される合計金額は，画面と同じように，財務局長のチェックがついているアイテムと加算，割引の値で算出しています
=> 購入報告のCSV出力

view/next-project/src/components/common/Title.tsx, view/next-project/src/pages/sponsoractivities/index.tsx
#639 
- 協賛金の回収済と未受取の絞り込み機能の実装 https://github.com/NUTFes/FinanSu/commit/699ed0e2f4d885bfa682664b78af35584a4b2ec2
- 協賛活動の並び替え機能の実装 https://github.com/NUTFes/FinanSu/commit/1d18a73ab229b0d8738f6c05f3a129b675424016
- 作成日時昇順(デフォルト) 
- 作成日時降順 : 作成日の新しい順 
- 更新日時昇順 : 更新日の古い順 
- 更新日時降順 : 更新日の新しい順
- 協賛金昇順 : 協賛金額合計の少ない順
- 協賛金降順 : 協賛金額合計の多い順
=> 協賛活動ページの協賛受取の絞り込みと並び替え機能の実装

view/next-project/src/components/purchasereports/DetailModal.tsx, view/next-project/src/pages/purchasereports/index.tsx
#644 
本番環境で購入報告のレコードに購入物品が登録されていないものがあり、
それが原因で現在エラーが出ている。
購入物品が登録されているレコードのみ処理を行うことで修正した。
購入報告ページとその詳細モーダルを修正した。
- 本番環境のAPIを呼び出し、購入報告ページが表示できるか確認する
- `src/pages/purchasereports/index.tsx`の`getPurchaseReportViewUrl`を以下に変更することで、呼び出せる
- `const getPurchaseReportViewUrl = 'https://finansu-api.nutfes.net/purchasereports/details';`
購入報告を追加する際、どこですり抜けているかは不明
おそらく購入申請にないものを報告する際の処理で何か問題が起きていると思われる
=> 購入報告ページのバグ修正

view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
resolve #650 
購入物品の登録の際に、物品名を入力せずに申請の確認へ進める仕様を改善。
物品名が未入力の場合には申請の確認ボタンがDisabledになるようにしました。
=> [feat] add validation  (#650)

view/next-project/src/components/common/Input/Input.tsx, view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/EditModal.tsx, view/next-project/src/constants/donationAmount.ts
resolve #649 
募金登録の際に金額の入力フォームにプルダウン(選択肢)を追加する。
datalist要素を利用して実装する。
- 学内募金の学内募金登録モーダルを開き、「金額」の入力フォームをクリックすると金額の候補が表示される。
- 登録した項目の編集モーダルを開き、「金額」の入力フォームをクリックすると金額の候補が表示される。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/datalist
=> 募金登録の金額入力フォームにプルダウンを追加する

view/next-project/src/components/purchasereports/PurchaseReportAddModal.tsx
resolve #651 
購入報告のところにある報告登録のモーダルから空の購入物品を登録できてしまうのを防ぐため、物品名が空の場合のバリデーションを設けた
- `URL`
スクリーンショット
- 購入報告で物品を追加しようとしたときにボタンが押せないようになっているか
- 物品名を入力したらボタンが押せるようになっているか
-
-
やまのPRを参考にしました。
=> 購入報告の追加モーダルにバリデーションを付けた(物品名が空白の時のみ)

api/docs/docs.go, api/externals/controller/purchase_report_controller.go, api/externals/repository/purchase_report_repository.go, api/internals/usecase/purchase_report_usecase.go, api/router/router.go
resolve #664
- 購入報告のapiを作成
- `/purchasereports/details/:year`
- swaggerにapiの追加
- swaggerにアクセスする `http://localhost:1323/swagger/index.html#/`
- swaggerでpurchase_reportsの`/purchasereports/details/:year`を実行する。
- 指定した年度範囲のレコードが取得できるか
=> [feat]購入報告の年度取得api作成

api/docs/docs.go, api/externals/controller/fund_information_controller.go, api/externals/repository/fund_information_repository.go, api/internals/usecase/fund_information_usecase.go, api/router/router.go
resolve #668
年度別でfund_informations/detailsを取得するAPIを作成しました。
- `URL`
スクリーンショット
- upした後に[swagger](localhost:1323/swagger/index.html#/)にアクセスしてfundinformations/details/[year]を探す
- あったらtry itからyearに2024を指定して実行しスクショのように結果が返ってくるか確認する
- 2023に関しては紐づくデータがないためnullが返ってくる。
- 確認したい場合はyear_periodsの2023の終了日を変更するか、2023に新しいデータを追加してください
ByYearだったり、ForPeriodsだったりで統一感ないですがどちらかがいいでしょうか。
=> [feat] 年度別のfund_informationsを取得するAPIの作成

api/docs/docs.go, api/externals/controller/activity_controller.go, api/externals/repository/activity_repository.go, api/internals/usecase/activity_usecase.go, api/router/router.go
resolve #673 
協賛活動の年度別に取得するAPIを作成しました
- `URL`
スクリーンショット
- `docker compose up`でswaggerを開き**/activities/details/{year}**を探す
- yearを指定して実行し結果が返ってくるか確認してください
- 2023にはデータがなくnullが返ってきます。
=> [feat] 年度別に協賛活動を取得するAPIの作成

api/docs/docs.go, api/externals/controller/sponsor_controller.go, api/externals/repository/sponsor_repository.go, api/internals/usecase/sponsor_usecase.go, api/router/router.go
resolve #675
年度別に指定したsponsorを全権取得するAPIを作成しました。
- `URL`
スクリーンショット
- swaggerを開き、sponsors/{year}を見つけてください
- 年度を指定して実行でデータを取得できたら成功です。
- 2024にのみデータが存在しています。他の年度でも動作するか確認したいときはlocalhost:3000/yearperiodsで年度を変更して確認してください
余談ですがsponsorのスペル間違ったまま作業してブランチ名をsponserにしてしまいました。誤解なきようお願いします。
=> [feat] 年度で指定されたsponsorsを取得する

view/next-project/src/pages/purchasereports/index.tsx
resolve #680 
全年度取得してフィルターする仕組みから、各年度の選択毎に取得するように修正。
- FinanSuをローカルで立ち上げ、購入報告ページが表示できるかを確認する。
- 年度切り替えができて、表示されるかを確認する。
=> [fix] 各年度毎に取得するように修正

api/docs/docs.go, api/externals/controller/budget_controller.go, api/externals/repository/budget_repository.go, api/internals/usecase/budget_usecase.go, api/router/router.go, view/next-project/src/pages/budgets/index.tsx
resolve #676 
- 予算の年度切り合えAPI作成
- 予算ページの年度切り替え実装
- 支出ページの年度切り替え実装
- swaggerへアクセスし、`/budgets/details/{year}`で取得できるか確認
- FinanSuをローカルで立ち上げ、予算ページを表示できるか確認する
- 予算ページで予算と支出を確認する
=> [feat]予算支出ページの年度切り替え実装

view/next-project/src/pages/sponsors/index.tsx
resolve #678 
前回、年度別に取得するAPIを作成したのでそれに伴ってフロントでフィルターを掛けるのではなくバックで取得したデータを表示させるように変更した
- `URL`
スクリーンショット
- `docker compose up -d`でコンテナを立ち上げて`localhost:3000/sponsors`にアクセスし、年度の切替でデータの取得、切替がなされているか確認お願いします。
- consoleでsponsorsのurlを表示しているので、年度を変更した時に正しい年度のurlが確認できたら大丈夫だと思ってます。
- 2023年度にはデータはないです。`localhost:3000/yearperiods`で年度の編集ができるので2023年度の終了期間を変更すれば確認できると思います。
-
過去の遺物に疑問が2点あります。
- `import { useState as UseState, useEffect as UseEffect } from 'react';`でわざわざ別名を当てて定義しているのには意味があるのでしょうか。他のページではしてないようです。
- `onChange={(e) => setSelectedYear(e.target.value)}`下記コードが他のページでは`onChange={async (e) => { setSelectedYear(e.target.value); }}`とコーディングされています。syncを付けなくても動作するのですが何故つけているのでしょうか
=> [feat] 年度別に取得するAPIを使って表示させるように変更

view/next-project/src/pages/sponsoractivities/index.tsx
resolve #677 
協賛活動一覧ページにおいて、選択した年度のデータのみを取得するように修正。
↓ 24/03/05 New 「CSSを修正」
- http://localhost:3000/sponsoractivities にアクセスし、年度切り替えが行えるかを確認する。
- 項目の並べ替えやフィルター機能が働くかを確認する。
=> [fix] 各年度ごとに取得するように修正

view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx, view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx
resolve #698
- 購入申請の登録のスタイルの修正
- 登録の際に最後にまとめてPOSTをする→リロードすると虚無申請が生成されるバグ修正のため
- 不要な関数`deletePurchaseOrder`→最初に申請を生成しないため必要ない
- 購入申請の登録が問題なくできる
- 購入申請を追加中にリロードをすると虚無の申請が生成されないか
- あえて、変な処理をしてバグらないか
- 虚無申請↓
=> [fix]購入申請のバグ修正

view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx, view/next-project/src/pages/purchasereports/index.tsx
resolve #653  購入報告ページ「財務局長チェック」を削除し、列の幅を調節
- `URL`
スクリーンショット
-
-
-
=> [fix]列名削除、調整

view/next-project/src/components/sponsoractivities/EditModal.tsx
resolve #647 
協賛活動の編集モーダル変更がうまく反映されないバグの修正。
- `URL`
スクリーンショット
-協賛活動の編集モーダルで担当者を変更し、変更が反映されているか確認する
-
-
=> [fix]編集モーダルでユーザーが反映されないバグ修正

view/next-project/src/components/purchaseorders/EditModal.tsx, view/next-project/src/utils/createPurchaseOrderPdf.ts
resolve #701 
購入申請一覧ページで購入物品が何も登録されていないとき、見積書作成が行われないバグを修正する。
編集時にformDataListがnullによるエラーを回避する。
- FinanSuをローカルで立ち上げ、`http://localhost:3000/purchaseorders` へアクセスできることを確認する。
- 新たに申請登録を行い、購入期限を入力し、「購入物品の詳細入力」を押して次のモーダルへ進む。そこで何も入力せず、ページをリロードする。
- ページのリロードにより、添付画像のように購入物品が空の状態で登録されることを確認する。
- 登録された項目をクリックし、申請の詳細から「見積書」作成を押すことでPDFがダウンロードされ、添付画像のようになるかを確認する。
- また購入物品が登録されている項目に対しても見積書が正常に作成されるかを確認する。
- 購入物品が無い項目を編集しようとすると、添付画像のように再作成を促す文言が表示されるかを確認する。
=> [feat] purchaseItemが無い場合の表示を追加

view/next-project/src/components/fund_information/EditModal.tsx
resolve #663 
Issue内容は、担当者が各局の一番上の人になるバグの解消です。
しかし、教員の所属・教員名・担当者の局の項目でも同様のバグが発生していたため、まとめて修正しました。
修正内容は、各項目の初期値として登録される値を、既に登録されている内容から参照するように変更しました。
- FinanSuをローカルで立ち上げ、`http://localhost:3000/fund_informations` へアクセスできることを確認する。
- 登録項目の編集ボタンを押し、編集モーダルが開くことを確認する。
- 各項目を初期値以外のものに設定し、登録ボタンを押す。（スクショ画像を参考にしてください。）
- 登録できたことを確認して再度、編集ボタンを押し、登録内容が初期化されていないかを確認する。
(各項目が全て1番目の要素に初期化されていないか。)
24/03/29 更新：モーダルの展開時はpropsの値を表示し、セレクト要素の選択時にUseEffectの再レンダリングで教員名の初期値を設定するようにしました。もっと良い方法あれば教えて下さい。
=> [fix] 登録されたデータが編集モーダルに反映されるよう修正

.gitignore, view/next-project/src/components/common/Select/Select.tsx, view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/OpenAddModalButton.tsx, view/next-project/src/pages/fund_informations/index.tsx
resolve #702
募金の登録を行うモーダルを開いた際に現在ログインしているユーザーの局、名前をデフォルトで表示させるようにしました。
- `URL`
スクリーンショット
- localhost:3000/fund_informationsで募金の新規登録ボタンをクリックする
- そこに出てきたモーダルにある**担当者の局、名前がログインしているユーザーであるか**確認お願いします
- テストアカウントを使っている場合はすべて総務局になっているので、ユーザーを新しく作成して試してもらえると分かりやすいと思います
=> [fix] 募金登録モーダルを現在ログインしているユーザー情報に変更

api/docs/docs.go, api/externals/controller/expense_controller.go, api/externals/repository/expense_repository.go, api/internals/domain/expense.go, api/internals/usecase/expense_usecase.go, api/router/router.go, view/next-project/src/components/budgets/DetailModal.tsx, view/next-project/src/components/purchaseorders/OpenAddModalButton.tsx, view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx, view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx, view/next-project/src/components/purchasereports/PurchaseReportConfirmModal.tsx, view/next-project/src/components/purchasereports/PurchaseReportItemNumModal.tsx, view/next-project/src/pages/budgets/index.tsx, view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/pages/purchasereports/index.tsx, view/next-project/src/type/common.ts
resolve #715 
- 購入報告ページで購入していない物品を登録する際に、購入した局・(団体)の選択肢を年度ごとに変更するようにした
- デフォルトは最新年度
- 購入報告ページを開く
- 購入報告の登録→申請していない物品を登録
- 年度を切り替えると購入した局・団体が切り替わるか確認する
=> 購入報告の登録時に支出のフィルターをかける

api/docs/docs.go, api/externals/controller/expense_controller.go, api/internals/domain/expense.go, api/internals/usecase/expense_usecase.go, api/router/router.go, view/next-project/src/components/purchaseorders/OpenAddModalButton.tsx, view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx, view/next-project/src/pages/purchaseorders/index.tsx, view/next-project/src/type/common.ts
resolve #708
購入申請ページの新規登録モーダルにて、支出欄を年度別に切り替えられるようにしました
- `URL`
スクリーンショット
- purchaseoordersの登録をクリックし、購入したい局、団体が年度別によって切り替わるか
-
-
適当にpropsを投げまくっているためコードよく見てほしいです
=> [fix] 年度別に支出の選択欄を選べるように変更

api/internals/domain/expense.go, view/next-project/src/components/purchaseorders/OpenAddModalButton.tsx, view/next-project/src/components/purchaseorders/PurchaseItemNumModal.tsx, view/next-project/src/pages/purchaseorders/index.tsx
resolve #719 
購入申請ページにある申請登録の購入したい局・団体を年度別に選択できるようにしました。
デフォルトは最新年度になっています
それに伴って、新たに**年度**という項目を追加しました
propsにyearPeriodsを渡して処理を行っています
また、api作成時にcommon.tsに不必要な定義をしていて削除し忘れていたので消しました。
- `URL`
スクリーンショット
- 購入申請(purchaseorders)に行き、申請登録でスクリーンショットのような画面になっているか
- 年度を切り替えると購入したい局・団体も切り替わるか
- nullの場合、局・団体が登録されていませんと表示されエラーが返ってこないか
=> 申請登録の購入したい局を年度別で選択できるように修正

view/next-project/src/components/purchasereports/PurchaseReportAddModal.tsx, view/next-project/src/components/purchasereports/PurchaseReportItemNumModal.tsx
resolve #722 
- 購入報告の登録の際に、購入報告ページで報告登録→申請していない物品を登録する→報告へ進む
- 物品登録中にリロードをすると、虚無に購入申請と物品が登録されるため、最後にまとめて登録するようにした
この画面でリロードすると、虚無の申請と物品が登録されていた
- 購入報告ページを開く
- 報告登録→申請していない物品を登録する→報告登録へ進む
- 最後まで登録し、データが問題なく登録できているか確認する
- 購入報告と購入申請と購入物品
- 報告登録→申請していない物品を登録する→報告登録へ進むでページをリロードし、購入申請ページに移動し、虚無の申請が作成されていないか確認する
- 購入報告の登録周りを触ってみてバグがないか確認してください
- おかしな点があれば、コメントしてください
=> [feat]購入報告登録のバグ修正

view/next-project/src/components/common/MultiSelect/MultiSelect.tsx, view/next-project/src/components/common/SearchSelect/SearchSelect.tsx, view/next-project/src/components/common/SearchSelect/index.ts, view/next-project/src/components/common/index.ts, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx, view/next-project/src/pages/sponsoractivities/index.tsx
resolve #743 
- 協賛企業の増加に伴い、optionを選ぶことが大変になっているため、ドロップダウンに検索機能を追加した。
- react-selectがデフォルトで検索機能がついているため、selectタグを移行した。
- 協賛活動の登録と編集で実装した。
- 検索は文字列の部分一致である
=> 協賛活動の企業のドロップダウンに企業の検索機能を追加した

view/next-project/src/components/common/index.ts, view/next-project/src/components/sponsoractivities/DetailPage2.tsx, view/next-project/src/components/sponsoractivities/UploadFileModal.tsx, view/next-project/src/pages/reset_password/[id]/index.tsx, view/next-project/src/pages/reset_password/request/index.tsx
resolve #754
画像を登録中でもボタンをクリックできてしまうので画像登録中はloadingを出現させてなおかつdisabledを付与しました。
あと,importのところまとめたかったので修正しました。
- `URL`
スクリーンショット
- 協賛活動の画像登録モーダルで画像を登録した時にloadingの画面が出現しているか
- 画像登録中にボタンがクリックできないようになっているか
-
=> 画像登録時にloadingを出現させた

view/next-project/src/components/fund_information/AddModal.tsx
resolve #762 
- 募金登録時にログインしているユーザーを初期値にするように設定していたが、局を変更すると、元々の局に戻れないバグがあったため修正した。
- ユーザーが選択されていない時に登録ボタンを押せないようにバリデーションを追加した。
- 局を変更して戻して、再び表示されるか確認する。
- 例：(元々)情報局→総務局→情報局 で情報局の名前が表示されるか
- ユーザーがない局(デフォルトだと企画や制作を選択した際にバリデーションがかかるか)
=> [fix]募金登録時のバグ修正

view/next-project/src/pages/500.tsx
resolve #768 
- 500エラーページの作成
- サーバーエラーのページの作成
- FinanSuライクな感じでお願いします
|PC表示|モバイル表示|
|---|---|
|![FireShot Capture 007 -  - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/33c04be1-df9a-4fd3-bf2a-b8b36bd79fb5)|![FireShot Capture 008 -  - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/5e2f61bb-ea70-4907-b1ce-fbad3ffd1bae)|
開発時はデフォルトのエラーが表示されるため、docker-compose.ymlの変更が必要です。`npm run build && npm run start`
```
export async function getServerSideProps() {
throw new Error('サーバーエラー');
}
```
上記のようなコードをindex.tsxなどに入れてページへアクセスする。
=> [feat] 500ページの作成

api/externals/repository/activity_repository.go, api/externals/repository/fund_information_repository.go, view/next-project/src/pages/sponsoractivities/index.tsx
resolve #782
デフォルトの表示を降順にするためにsql文のorder byをidからupdated_at DESCに変更した。
ps.協賛活動のフィルターのデフォルトが作成日時昇順になっていたため下記の順番に変更した
> 更新日時降順
>  更新日時昇順
> 作成日時降順
> 作成日時昇順
> 協賛金降順
> 協賛金昇順
- `URL`
スクリーンショット
- activity,fund_infomationのデータが降順で取得されているか
- ps.協賛活動のフィルターが正常に動作しているか
-
協賛活動のフィルターがの作成日時の昇順降順動いてないかも修正します。→しました
=> 協賛活動、学内募金の表示をupdated_atの降順にした

view/next-project/src/components/purchasereports/DetailEditModal.tsx, view/next-project/src/components/purchasereports/EditModal.tsx, view/next-project/src/components/purchasereports/OpenEditModalButton.tsx
resolve #781 
購入報告ページにおいて、購入した局と期限日を変更できるモーダルを追加しました。
編集ボタンを押すと選択モーダルが開き、修正内容によってモーダル展開のボタンを選択する仕組みです。
|![FireShot Capture 011 - 購入報告一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/16235d2f-4afc-4f8c-a2f8-cae6cc54e62d)|![FireShot Capture 012 - 購入報告一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/b93801c1-ac60-4783-8091-b4306e8e762f)|
|---|---|
=> 購入報告ページで申請した局&期限日を編集可能にする。

mysql/db/users.sql, view/next-project/src/pages/fund_informations/index.tsx
resolve #798
- 一般ユーザー(role_id:1)を募金ページが見れないようにした
- 一般ユーザー場合は購入申請ページへ飛ばされる
- seedデータのtest4@example.comは財務局員権限でなかったため修正した
- test1~test4でログインして募金ページにアクセスする
- 今までの初期データはtest4は一般ユーザーであっため注意する(このブランチでは修正済み)
=> 一般ユーザーは募金ページを閲覧不可にした

view/next-project/.storybook/main.ts, view/next-project/src/components/purchaseorders/DetailModal.tsx, view/next-project/src/components/purchaseorders/index.ts, view/next-project/src/stories/purchaseorders/DeleteModal.stories.tsx, view/next-project/src/stories/purchaseorders/DetailModal.stories.tsx, view/next-project/src/stories/purchaseorders/EditModal.stories.tsx, view/next-project/src/stories/purchaseorders/OpenAddModalButton.stories.tsx, view/next-project/src/stories/purchaseorders/OpenDeleteModalButton.stories.tsx, view/next-project/src/stories/purchaseorders/OpenEditModalButton.stories.tsx, view/next-project/src/stories/purchaseorders/PurchaseItemNumModal.stories.tsx, view/next-project/src/stories/purchaseorders/PurchaseOrderAddModal.stories.tsx
resolve #803 
既存のコンポーネントに対応した.stories.tsxファイルを作成する。
- DeleteModal.stories.tsx
- DetailModal.stories.tsx
- EditModal.stories.tsx
- OpenAddModalButton.stories.tsx
- OpenDeleteModalButton.stories.tsx
- OpenEditModalButton.stories.tsx
- PurchaseltemNumModal.stories.tsx
- PurchaseOrderAddModal.stories.tsx
あと`FinanSu/view/next-project/src/stories`の中を階層構造にするためにmain.tsをちょっと編集しました。
- Storybookを起動してスクリーンショットのようなカタログが表示されるか
-
このブランチがmergeされるとstoriesファイルの中を階層構造にできるようになる…はず…
=> 既存コンポーネントをStorybook上に表示する（/purchaseorders）

view/next-project/src/components/fund_information/index.ts, view/next-project/src/stories/AddModal.stories.tsx, view/next-project/src/stories/DeleteModal.stories.tsx, view/next-project/src/stories/EditModal.stories.tsx, view/next-project/src/stories/OpenAddModalButton.stories.tsx, view/next-project/src/stories/OpenDeleteModalButton.stories.tsx, view/next-project/src/stories/OpenEditModalButton.stories.tsx
resolve #797 
既存のコンポーネントをStoribookに表示する。
今回表示させたのは以下の通り。
- AddModal.stories.tsx
- DeleteModal.stories.tsx
- EditModal.stories.tsx
- OpenAddModalButton.stories.tsx
- OpenDeleteModalButton.stories.tsx
- OpenEditModalButton.stories.tsx
また、.storiesファイル側での呼び出し？を簡単にするために/fund_information内にindex.tsを作成した。
- Storybookを起動して上記のコンポーネントを見ることができるか
- index.tsの追加に問題はないか
- `AddModal.stories.tsx`と`EditModal.stories.tsx`はchatGPTを使って生成した。問題のあるコード・記述はないか
`FinanSu/view/next-project/src/stories`内のファイルが多くなってきた。階層構造に分けた方がいいかも。
=> 既存コンポーネントをStorybookに表示する（/fund_information）

docker-compose.prod.yml, docker-compose.yml, view/next-project/src/pages/api/minio.tsx
- finansuのバケットの作成(開発環境でない場合)
- バケット作成時にアクセスポリシーをpublicにする(FinanSu上で表示するため)
- 不必要なprodの環境変数の削除
- /tmpディレクトリを削除
- イメージとボリュームをけして、ビルドとアップ
- ログインして、協賛活動から画像をアップロードできればおけ
- 新入生も入ってきて色々面倒な設定させるのが良くないのでしました
- このブランチをローカルにpullしてください
- `git pull`
- `git switch initial-minio-settings` 
- `make del-vol-run`でボリュームを削除して、コンテナをビルド&起動してください
- 少し待つとlocalhost:3000でFinanSuにアクセスできると思います
- slackの#develop-finansuでピン留めされているでデフォルトユーザーでログインしてください
- (ここでログインできない時はapiとdbの接続がうまくいっていない場合があるので、その場合apiコンテナを再起動してください、docker destopでリロードボタンを押すのが楽です、apiコンテナのlogでechoと出たら問題ありません)
- ログインができたら購入申請一覧に行きます
- 左のメニューバーの渉外局の下の協賛活動をクリック
- テスト企業などのデータがあると思います、クリックするとその詳細が表示されます
↓この画面
- 右下の矢印ボタンをクリック
↓ このような画面になります
- +ボタンをクリック
- 広告登録ボタンをクリック
- ファイルを選択からてきとうな画像ファイルをアップロードしてみてください
- 登録ボタンを押して「保存しました」と表示されたら動作確認オッケーです
- …
=> minioのバケット作成やキーの作成を不要にする

view/next-project/src/pages/users/index.tsx
resolve #827 
- /users ページで学科によるフィルターを実装
- /teachers を参考に以下の点を変更
- selectedBureauというstateを追加
- ドロップダウンメニューの追加
- selectedBureauに基づいてsetFilterUsersで表示するユーザを変更
- `URL`
スクリーンショット
- 絞り込みが正しく動くか
- ユーザの編集の機能が正しく動くか
- ユーザ削除の機能が正しく動くか
/teachers を参考に変更した
=> [feat]ユーザ一覧ページにおいて学科ごとのフィルタ機能を追加

Makefile, docker-compose.db.yml, docker-compose.local-prod.yml, docker-compose.yml, view/local-prod.Dockerfile
resolve #821 
- apiとdbが接続できない時、apiコンテナを再起動する必要があったので対策をした
アプリ(view, api)とDB(db, minio)でdocker-compose.ymlファイルを分割した
- 理由
- apiが起動する際にdbが起動中で接続できないため
- 現在はdocker compose downで全てのコンテナを閉じてしまう→再起動の度に負荷がかかる
- デメリット
- dbの起動忘れなどが発生するかも
- 起動するまでに `make run-db,  make build, make run`の3つのコマンドが必要になる
db側は基本ずっと立ち上げとくイメージ(閉じてもいい)
makeコマンドの修正(run-db, stop-dbなど)
- 既存のdockcer ネットワーク、イメージ、ボリュームを削除
- ルートディレクトリにfinansu.envがあるか確認する
- `make run-db`、　`make build`、 `make run`でFinanSuが起動するか
- アプリ側を停止して、`make run`で起動するか(Goがdbと繋がるか)
- 色々動かして、変なエラーが出ないか
=> APIがDBとの接続できない問題の解消

api/docs/docs.go, api/externals/controller/teacher_controller.go, api/externals/repository/teacher_repository.go, api/internals/usecase/teacher_usecase.go, api/router/router.go
resolve #815 
disabledを掛けるためにfund_informationに登録されているteacher.idを取得しました。
取得したidは配列で返すようにしています。このままフロントで使えると思います。
- `URL`
スクリーンショット
- `swaggerを開いて、/teachers/fundRegistered/{year}`にとんでください
- yearパラメータに2024と入力して、スクショのような結果が返ってくるか
- 他のパラメータを指定してもシーズデータに存在しないためnullが返ってきます
-
命名てきとうにしたので要確認でお願いします
=> [feat] 年度別で募金登録済みの教員Idを配列で返すAPIの作成

view/next-project/src/components/fund_information/AddModal.tsx, view/next-project/src/components/fund_information/EditModal.tsx, view/next-project/src/components/fund_information/OpenAddModalButton.tsx, view/next-project/src/components/fund_information/OpenEditModalButton.tsx, view/next-project/src/pages/fund_informations/index.tsx
resolve #837 
- 登録済教員のid配列をAPIで取得し、学内募金の登録、編集時に選択不可にした
- 軽微なリファクタリング
- `URL`
スクリーンショット
- 募金の登録、編集を触って動作がおかしくないか検証する
- 登録済教員が選択不可になっているか
=> 学内募金の登録・編集時に登録済の教員を選択できないようにする

view/next-project/src/components/purchaseorders/DetailModal.tsx, view/next-project/src/components/purchaseorders/EditModal.tsx, view/next-project/src/components/purchaseorders/PurchaseOrderAddModal.tsx, view/next-project/src/components/purchasereports/DetailModal.tsx, view/next-project/src/components/purchasereports/PurchaseReportConfirmModal.tsx
resolve #840 
- urlがない場合、表示しないようにした
- `URL`
スクリーンショット
- 購入申請ページ、登録、編集で未登録時にリンクアイコンが表示されないか
- 購入報告ページ、登録で未登録時にリンクアイコンが表示されないか
-
=> urlが登録されていないものは非表示にする

api/docs/docs.go, api/externals/controller/receipt_controller.go, api/externals/repository/receipt_repository.go, api/internals/di/di.go, api/internals/domain/receipt.go, api/internals/usecase/receipt_usecase.go, api/router/router.go, mysql/db/receipts.sql
resolve #842 
- receiptテーブルの作成 [レシートテーブルの作成](https://github.com/NUTFes/FinanSu/pull/843/commits/19d45c1adf655172b10e288947305a6e988063e5)
- APIの作成
- 基本のCRUD操作
- `/receipts/reports/{id}` 購入報告IDを指定してレコードのGET
- swaggerの追加
- `URL`
- レシートテーブルを追加する
- swaggerでAPIが全て問題なく使えるか
- コードレビュー
=> 購入報告のレシート登録用のAPI作成

api/docs/docs.go, api/externals/controller/purhcase_order_controller.go, api/externals/repository/purchase_order_repository.go, api/internals/usecase/purchase_order_usecase.go, api/router/router.go, view/next-project/src/components/purchasereports/PurchaseOrderListModal.tsx
resolve #822
- 購入報告に登録されていない購入申請のdetailsを取得するAPIを作成
- swaggerへの追加
- フロントのパス修正
=> 報告未登録の申請取得APIの作成

view/next-project/src/components/purchaseorders/DetailEditModal.tsx, view/next-project/src/components/purchaseorders/EditModal.tsx, view/next-project/src/components/purchaseorders/OpenEditModalButton.tsx, view/next-project/src/pages/purchaseorders/index.tsx
resolve #813 
購入申請ページにおいて、購入した局と期限日を変更できるモーダルを追加しました。
編集ボタンを押すと選択モーダルが開き、修正内容によってモーダル展開のボタンを選択する仕組みです。
#784 と同様に作成しています。
| ![FireShot Capture 016 - 購入申請一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/2076dc80-fe69-4937-8929-579e19781bdf) | ![FireShot Capture 017 - 購入申請一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/9c2b41ee-89cb-44bc-a2bb-7a2d4063f95e) | ![FireShot Capture 018 - 購入申請一覧 - localhost](https://github.com/NUTFes/FinanSu/assets/131145590/8238d700-f46a-4700-9fa6-9c9456a44694) |
| -- | -- | -- |
=> 購入申請ページで申請した局と期限日を編集可能にする。

view/next-project/src/components/sponsors/index.ts, view/next-project/src/stories/sponsors/DeleteModal.stories.tsx, view/next-project/src/stories/sponsors/OpenAddModalButton.stories.tsx, view/next-project/src/stories/sponsors/OpenDeleteModalButton.stories.tsx, view/next-project/src/stories/sponsors/OpenEditModalButton.stories.tsx, view/next-project/src/stories/sponsors/SponsorAddModal.stories.tsx, view/next-project/src/stories/sponsors/SponsorEditModal.stories.tsx
resolve #806 
以下のcomponents/sponsors/stories.tsxのファイルを追加
DeleteModal.stories.tsx
OpenAddModalButton.stories.tsx
OpenDeleteModalButton.stories.tsx
OpenEditModalButton.stories.tsx
SponsorAddModal.stories.tsx
SponsorEditModal.stories.tsx
以下のstories/sponsors/index.tsのファイルを追加
index.ts
- storybook上でsponsorsの各項目が既存コンポーネントの通り表示されているか
- 他のプログラムに悪影響があるエラーがないか
-
=> Storybookの既存コンポーネントを表示する(/sponsors)

api/docs/docs.go, api/externals/repository/sponsor_style_repository.go, api/internals/domain/sponsor_style.go, api/internals/usecase/activity_usecase.go, api/internals/usecase/sponsor_style_usecase.go, mysql/db/sponsor_styles.sql
resolve #850
sponsorStyleに論理削除を導入しました。
- sponsorStylesのカラムにis_Deletedを追加
- 削除のクエリ文をis_deletedをtrueに変えるように修正
- GETSのクエリ文をis_deletedがfalseのもののみに修正
- `URL`
スクリーンショット
- swaggerでsponsorStylesの各操作を実行して、論理削除ができているか
- sponsorStylesを紐づけているところで500エラーが発生しないか
-
確認お願いします。
=> sponsorStylesの削除方法を論理削除に変更した

view/next-project/src/components/yearperiods/index.ts, view/next-project/src/stories/yearperiods/AddModal.stories.tsx, view/next-project/src/stories/yearperiods/DeleteModal.stories.tsx, view/next-project/src/stories/yearperiods/EditModal.stories.tsx, view/next-project/src/stories/yearperiods/OpenAddModalButton.stories.tsx, view/next-project/src/stories/yearperiods/OpenDeleteModalButton.stories.tsx, view/next-project/src/stories/yearperiods/OpenEditModalButton.stories.tsx
resolve #810 
既存コンポーネントを表示する.storiesファイルを追加する
以下のファイルを表示することができるか。
constants.tsがまだdevelopブランチになかったので定数は使いませんでした。
=> 既存コンポーネントを表示する.storiesファイルを追加する（/yearperiods）

view/next-project/src/components/auth/index.ts, view/next-project/src/stories/auth/SignInView.stories.tsx, view/next-project/src/stories/auth/SignUpView.stories.tsx
resolve #860
authコンポーネントを表示するためのstories.tsxファイルを追加する。
以下のコンポーネントがStorybook上で表示できるか確認する。
=> 既存コンポーネントをStorybook上に表示する（/auth）

view/next-project/src/components/sponsoractivities/DetailModal.tsx, view/next-project/src/components/sponsoractivities/DetailPage2.tsx, view/next-project/src/components/sponsoractivities/UploadFileModal.tsx, view/next-project/src/pages/api/advertisements.tsx, view/next-project/src/pages/sponsoractivities/index.tsx
resolve #862 
- minioのディレクトリ整理 /finansu/{年度}/advertisements/{filename}に格納される
- 広告データが変更・削除された時minioのオブジェクトも削除
- `URL`
=> minioのディレクトリ整理&広告データが変更・削除された時minioのオブジェクトも削除

view/next-project/src/components/purchasereports/DetailEditModal.tsx, view/next-project/src/components/purchasereports/OpenEditModalButton.tsx, view/next-project/src/pages/purchasereports/index.tsx
resolve #866 
購入報告ページのDetailEditModalにおいてモーダル側でデータを取得せず、ページから受け取る方法へ変更
=> 購入報告ページのDetailEditModalのデータ取得方法を修正

view/next-project/src/components/common/EditButton.tsx, view/next-project/src/components/common/Input/Input.tsx, view/next-project/src/components/sponsoractivities/AddPdfDetailModal.tsx, view/next-project/src/components/sponsoractivities/EditInvoiceModal.tsx, view/next-project/src/components/sponsoractivities/OpenEditInvoiceModalButton.tsx, view/next-project/src/components/sponsoractivities/index.ts, view/next-project/src/type/common.ts, view/next-project/src/utils/createSponsorActivitiesInvoicesPDF.tsx
resolve #868 
- 請求書でスタイルや担当者名などを発行前に編集できるようにした
- 新しく請求書用の型を作った
- `URL`
- 請求書の発行に問題がないか
- 正しく請求書を編集できるか
- エラーが起きないか
=> 請求書の編集機能の追加

view/next-project/src/components/purchasereports/UploadFileModal.tsx, view/next-project/src/pages/api/receipts.tsx
resolve #870
- レシート登録時にファイル名を動的に生成するようにした
- iphoneなどで写真を撮って登録する際、ファイル名はimage.pngになってしまうため、その対応
- `URL`
スクリーンショット
- minio上でレシートのファイル名が統一されているか
- レシートの登録、変更、削除などの動作が問題ないか
=> レシート登録時にファイル名を動的生成

.gitignore, view/next-project/src/components/sponsoractivities/AddPdfDetailModal.tsx, view/next-project/src/components/sponsoractivities/DeleteModal.tsx, view/next-project/src/components/sponsoractivities/DetailModal.tsx, view/next-project/src/components/sponsoractivities/EditInvoiceModal.tsx, view/next-project/src/components/sponsoractivities/EditModal.tsx, view/next-project/src/components/sponsoractivities/FilterModal.tsx, view/next-project/src/components/sponsoractivities/PaymentDayModal.tsx, view/next-project/src/components/sponsoractivities/SponsorActivitiesAddModal.tsx, view/next-project/src/components/sponsoractivities/UploadFileModal.tsx
#872 
resolve #872
協賛活動ページのウィンドウを画面外タップをすると閉じるようにする
- `URL`
スクリーンショット
- 協賛企業ページで、各モーダルが画面外タップで閉じるようになっているか
-
-
=> [feat]協賛活動ページで画面外タップでモーダルを閉じるように変更

view/next-project/src/components/common/Loading/Loading.tsx, view/next-project/src/components/sponsoractivities/UploadFileModal.tsx, view/next-project/src/pages/api/advertisements.tsx
resolve #876 
- データを直接minioへ送信するのではなく，クライアント側でデータを分割し，サーバーで結合してからminioへ送信するように修正しました．
- Loadingコンポーネントに進捗属性を追加
- 1GB以上のファイルを防ぐバリデーションを追加
(検証用に使った画像のサイト：https://sample-img.lb-product.com/)
Zeenの記事のようにしなくても解決できました！
アップロードするまで，ちょっと遅いかも...
~~FinanSuのCloudflare Tunnelを利用するためのjsonファイルとcert.pemファイルが見つからなかったため，`https://bingo.nutfes.net/`で検証しました．確認方法やFinanSuのを知りたいです．~~
(普通にsettingsに入ってた…)
=> 100MB以上の広告データがアップロードできない問題を修正

api/go.mod, openapi/openapi.yaml
resolve #901 
- 予算管理ページで必要なAPIをopenapiで定義した
- `/financial_records`
- 支出元　局など 
- `/divisions`
- 部門 
- `/festival_items `
- 物品 
- `URL`
- apiの定義が正しいか確認する
-
apiは実装していないです。
[figma](https://www.figma.com/design/9EV5ju2KhWYLWGavEnkjvb/%5B%E4%BD%9C%E6%88%90%E4%B8%AD%5D%E6%96%B0%E8%B3%BC%E5%85%A5%E5%A0%B1%E5%91%8A%E3%83%9A%E3%83%BC%E3%82%B8?node-id=0-1&p=f&m=dev)
[ER図](https://app.diagrams.net/#G1_AjwolLBUxg1x7mvkPWBYchkTYSfV6Bk#%7B%22pageId%22%3A%22K3osBV1VVUgABwI3_Tnj%22%7D)
=> 予算管理ページのapi定義

api/drivers/db/db.go, api/externals/controller/festival_item_controller.go, api/externals/controller/financial_record_controller.go, api/externals/repository/abstract/abstract_repository.go, api/externals/repository/festival_item_repository.go, api/externals/repository/financial_record_repository.go, api/generated/openapi_gen.go, api/internals/di/di.go, api/internals/usecase/festival_item_usecase.go, api/internals/usecase/financial_record_usecase.go, api/router/router.go, openapi/openapi.yaml, view/next-project/src/generated/hooks.ts, view/next-project/src/generated/model/index.ts
resolve #905
- 予算管理の物品のAPIを作成した
- openapiの定義修正
- GETでクエリパラメータ追加 `year` `division_id`
- 
- GET
- `year`、`division_id`で指定した年度のデータを全件取得
- (なしだと全件）
- POST
-  name、divisionId、amount、memoをbodyパラメータでfestival_items、item_bugetのレコードを作成する
- PUT
-  idをパスパラメータ
-  name、divisionId、amount、memoをbodyパラメータでfestival_items、item_bugetのレコードを修正する
- DELETE
-  パスパラメータでidを指定してfestival_items、item_bugetを削除する
- swaggerでfestival_itemのAPIを叩く
- POSTでデータが作成できるか
- PUTでデータが修正できるか
- DELETEでデータの削除ができるか
- GETでデータの取得ができるか
- item_budgets、buy_reportsにデータを取得し、GETで集計ができているか確認する
- 局や部門idが存在しないと外部制約エラーで作成できないです
=> [予算管理]購入物品APIの作成

api/externals/controller/festival_item_controller.go, api/externals/repository/festival_item_repository.go, api/generated/openapi_gen.go, api/internals/domain/festival_item.go, api/internals/usecase/festival_item_usecase.go, api/router/router.go, openapi/openapi.yaml, view/next-project/src/generated/hooks.ts, view/next-project/src/generated/model/index.ts
resolve #914
- ここの一覧表示のAPIです
- usecaseの処理が長くなったので、1つだけで出します
- GET `/festival_items/details/{user_id}`
- userが属する部門（division)の予算・支出をなどを返します 
- クエリパラメータでyearを渡すと、年度のものを返します
```
[
{
"divisionTotal": {
"budget": 100000,
"expense": 10000,
"balance": 90000
},
"financialRecordName": "企画局",
"divisionName": "ビンゴ部門",
"festivalItems": [
{
"festivalItemTotal": {
"budget": 100000,
"expense": 10000,
"balance": 90000
},
"festivalItemName": "ビンゴ景品",
"buyReports": [
{
"id": 1,
"buyReportName": "段ボール",
"amount": 1000,
"reportDate": "2024-01-01",
"status": "確認中"
}
]
}
]
}
]
```
- `URL`
スクリーンショット
-
- 動作確認のためにテーブルにデータ追加する必要があります
- financial_records
- divisions
- user_groups
- festival_items
- item_budgets
- buy_reports
- buy_status
=> [マイページ]部門予算・詳細取得

api/externals/controller/buy_report_controller.go, api/externals/repository/buy_report_repository.go, api/internals/usecase/buy_report_usecase.go, api/router/router.go
resolve #0
buy_reportのAPIを作成しました。
- `URL`
スクリーンショット
- 動作確認
- コードレビュー
-
予算管理フロント作成から切ってます
=> buy_report Get details & Put status APIの作成

api/externals/repository/buy_report_repository.go, api/externals/repository/income_expenditure_management_repository.go, api/internals/di/di.go, api/internals/domain/buy_report.go, api/internals/usecase/buy_report_usecase.go
resolve #0
- PUT
[/buy_report/status/{buy_report_id}](http://localhost:8000/#/buy_report/put_buy_report_status__buy_report_id_) の処理を修正した
- 精算済みになった際に収支管理のデータがない場合はincome_expenditure_managementsとbuy_report_income_expenditure_managementsにデータを追加する
- `URL`
- 購入報告→精算済み→収支管理に反映されるかを確認する
-
-
=> 購入報告で精算完了になった際に収支管理に追加するようにした

view/next-project/src/components/purchasereports/CheckSettlementConfirmModal.tsx, view/next-project/src/components/purchasereports/OpenCheckSettlementModalButton.tsx, view/next-project/src/components/purchasereports/index.ts, view/next-project/src/pages/purchase_report_list/index.tsx
購入報告一覧でのチェックボックスのルール変更と清算完了確認モーダルの追加
他のモーダルを参考に見よう見真似でやってみました
=> 購入報告一覧の清算完了確認モーダルの追加
